/*
    SPDX-FileCopyrightText: 2026 Bree Spektor
    SPDX-FileCopyrightText: 2026 Latte Dock contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

//! EX-14 DropEventClassifier (docs/tracking/QML_EXTRACTION_PLAN.md). Pins the
//! drag/drop mime classification of BOTH consumers (containment
//! DragDropArea, plasmoid MouseHandler) over shared vectors - the
//! drift-regression shape - plus the decision ladders, tools.js
//! insertIndexAt and the onDragMove suppression routing, and the
//! DropClassifierTools wrapper boundary (compiled in, sanitized).
//!
//! Expectation provenance: every expected value was derived by
//! hand-executing the shipped QML/JS bodies (byte-identical to Qt5
//! f0ad7b23 - verdicts in docs/agent-logs/EX-14.md), not generated by
//! running the implementation under test.

#include "../../declarativeimports/core/dropclassifiertools.h"
#include "../../declarativeimports/core/units/dropclassifier.h"

#include <QJSEngine>
#include <QJSValue>
#include <QMimeData>
#include <QRegularExpression>
#include <QUrl>
#include <QtTest>

Q_DECLARE_METATYPE(Latte::DropClassifier::TasksDragMoveSnapshot)
Q_DECLARE_METATYPE(Latte::DropClassifier::TasksDragMoveAction)

using namespace Latte;

namespace {

//! DragDropArea/MouseHandler run against desktop-file and document
//! urls; the test predicate mirrors extendedInterface.isApplication's
//! contract at the granularity the classifier consumes it
bool isDesktopFileUrl(const QUrl &url)
{
    return url.toString().endsWith(QLatin1StringView(".desktop"));
}

}

class DropClassifierTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    void classification_truthTable_bothConsumers_data();
    void classification_truthTable_bothConsumers();

    void containmentEnterLadder_truthTable();
    void containmentMoveLadder_truthTable();
    void containmentDropLadder_truthTable();
    void tasksDropLadder_truthTable();
    void separatorDropPosition_hoveredOrRowHead();

    void insertIndexAt_table_data();
    void insertIndexAt_table();

    void dragMoveRouting_table_data();
    void dragMoveRouting_table();
    void dragMoveRouting_reorderAlwaysCarriesTarget();

    void wrapper_classifiesRealMimeData();
    void wrapper_predicateExceptionIsSurfacedNotSwallowed();
    void wrapper_refusesNullMimeData();
    void wrapper_refusesNonCallablePredicate();
    void wrapper_decidesDragMoveFromSnapshotMap();
    void wrapper_refusesMalformedDragMoveSnapshots_data();
    void wrapper_refusesMalformedDragMoveSnapshots();
    void wrapper_separatorDropPosition();
};

void DropClassifierTest::classification_truthTable_bothConsumers_data()
{
    QTest::addColumn<QStringList>("formats");
    QTest::addColumn<QString>("serviceData");
    QTest::addColumn<bool>("hasUrls");
    QTest::addColumn<QList<QUrl>>("urls");
    //! containment expectations
    QTest::addColumn<bool>("isTask");
    QTest::addColumn<bool>("isPlasmoid");
    QTest::addColumn<bool>("isSeparator");
    QTest::addColumn<bool>("isLatteTasks");
    QTest::addColumn<bool>("onlyLaunchers");
    //! plasmoid expectations
    QTest::addColumn<bool>("movingTask");
    QTest::addColumn<bool>("droppingOnlyLaunchers");
    QTest::addColumn<bool>("droppingSeparator");
    QTest::addColumn<bool>("droppingFiles");

    const QString taskFormat{DropClassifier::TaskButtonItemFormat};
    const QString serviceFormat{DropClassifier::PlasmoidServiceNameFormat};
    const QString uriList = QStringLiteral("text/uri-list");

    //! a taskbar button drag; onlyLaunchers is TRUE through the vacuous
    //! every() - faithful Qt5 quirk (the containment's enter ladder
    //! rejects task drags before the flag can matter)
    QTest::newRow("task drag")
            << QStringList{taskFormat} << QString() << false << QList<QUrl>{}
            << true << false << false << false << true
            << true << false << false << false;

    //! the widget-explorer plasmoid drop - the mime combo that later
    //! flows through containment main.qml onAppletAdded's masqueraded
    //! index; the tasks area must NOT accept it (falls through to the
    //! containment DropArea behind it)
    QTest::newRow("plasmoid drop (masqueraded-index flow)")
            << QStringList{serviceFormat} << QStringLiteral("org.kde.plasma.analogclock") << false << QList<QUrl>{}
            << false << true << false << false << false
            << false << false << false << false;

    QTest::newRow("latte separator drop")
            << QStringList{serviceFormat} << QStringLiteral("org.kde.latte.separator") << false << QList<QUrl>{}
            << false << true << true << false << false
            << false << false << true << false;

    QTest::newRow("audoban separator drop (Qt5 legacy id)")
            << QStringList{serviceFormat} << QStringLiteral("audoban.applet.separator") << false << QList<QUrl>{}
            << false << true << true << false << false
            << false << false << true << false;

    QTest::newRow("latte tasks applet drop")
            << QStringList{serviceFormat} << QStringLiteral("org.kde.latte.plasmoid") << false << QList<QUrl>{}
            << false << true << false << true << false
            << false << false << false << false;

    //! the containment matches a LINE of the newline-separated payload
    //! (View::mimeContainsPlasmoid splits); the plasmoid compares the
    //! WHOLE payload - faithful asymmetry between the two consumers
    QTest::newRow("multi-line payload containing a separator line")
            << QStringList{serviceFormat} << QStringLiteral("org.kde.plasma.kickoff\norg.kde.latte.separator")
            << false << QList<QUrl>{}
            << false << true << true << false << false
            << false << false << false << false;

    //! same asymmetry through a trailing newline: line-split ignores it,
    //! whole-payload comparison does not
    QTest::newRow("separator payload with trailing newline")
            << QStringList{serviceFormat} << QStringLiteral("org.kde.latte.separator\n") << false << QList<QUrl>{}
            << false << true << true << false << false
            << false << false << false << false;

    //! service format present but NOT first: the containment's presence
    //! rule still matches the name, both first-position rules do not
    QTest::newRow("service format present but not first")
            << QStringList{QStringLiteral("text/plain"), serviceFormat}
            << QStringLiteral("org.kde.latte.separator") << false << QList<QUrl>{}
            << false << false << true << false << true
            << false << true << false << false;

    QTest::newRow("all-application file drop")
            << QStringList{uriList} << QString() << true
            << QList<QUrl>{QUrl(QStringLiteral("file:///a/kate.desktop")), QUrl(QStringLiteral("file:///b/konsole.desktop"))}
            << false << false << false << false << true
            << false << true << false << false;

    //! one non-application url fails every(); the plasmoid then takes
    //! the files route
    QTest::newRow("mixed file drop")
            << QStringList{uriList} << QString() << true
            << QList<QUrl>{QUrl(QStringLiteral("file:///a/kate.desktop")), QUrl(QStringLiteral("file:///b/notes.txt"))}
            << false << false << false << false << false
            << false << false << false << true;

    QTest::newRow("plain document drop")
            << QStringList{uriList} << QString() << true
            << QList<QUrl>{QUrl(QStringLiteral("file:///b/notes.txt"))}
            << false << false << false << false << false
            << false << false << false << true;

    //! no urls, not a plasmoid drag: every() over the empty list is
    //! vacuously TRUE in both consumers - faithful Qt5 quirk; the
    //! plasmoid accepts the drag and urlsDropped([]) is a no-op
    QTest::newRow("plain text drag (vacuous every)")
            << QStringList{QStringLiteral("text/plain")} << QString() << false << QList<QUrl>{}
            << false << false << false << false << true
            << false << true << false << false;

    //! a task drag carrying urls: movingTask does NOT veto the files
    //! flag (only recognized launchers do) - faithful; the drop ladder
    //! still resolves to LeaveUnchanged/AddSeparator order first
    QTest::newRow("task drag with urls")
            << QStringList{taskFormat, uriList} << QString() << true
            << QList<QUrl>{QUrl(QStringLiteral("file:///b/notes.txt"))}
            << true << false << false << false << false
            << true << false << false << true;

    QTest::newRow("empty mime")
            << QStringList{} << QString() << false << QList<QUrl>{}
            << false << false << false << false << true
            << false << true << false << false;
}

void DropClassifierTest::classification_truthTable_bothConsumers()
{
    QFETCH(QStringList, formats);
    QFETCH(QString, serviceData);
    QFETCH(bool, hasUrls);
    QFETCH(QList<QUrl>, urls);

    const DropClassifier::MimeSnapshot mime{.formats = formats,
                                            .plasmoidServiceData = serviceData,
                                            .hasUrls = hasUrls,
                                            .urls = urls};

    const auto containment = DropClassifier::classifyContainmentDrag(mime, isDesktopFileUrl);
    QTEST(containment.isTask, "isTask");
    QTEST(containment.isPlasmoid, "isPlasmoid");
    QTEST(containment.isSeparator, "isSeparator");
    QTEST(containment.isLatteTasks, "isLatteTasks");
    QTEST(containment.onlyLaunchers, "onlyLaunchers");

    const auto tasks = DropClassifier::classifyTasksDrag(mime, isDesktopFileUrl);
    QTEST(tasks.movingTask, "movingTask");
    QTEST(tasks.droppingOnlyLaunchers, "droppingOnlyLaunchers");
    QTEST(tasks.droppingSeparator, "droppingSeparator");
    QTEST(tasks.droppingFiles, "droppingFiles");
}

void DropClassifierTest::containmentEnterLadder_truthTable()
{
    using Action = DropClassifier::ContainmentEnterAction;
    const DropClassifier::ContainmentDragFlags launchers{.onlyLaunchers = true};
    const DropClassifier::ContainmentDragFlags task{.isTask = true, .onlyLaunchers = true};
    const DropClassifier::ContainmentDragFlags plain{};

    //! rejection outranks everything, launchers-stealing outranks spacer
    QCOMPARE(DropClassifier::containmentDragEnterAction(task, false, true, true), Action::Reject);
    QCOMPARE(DropClassifier::containmentDragEnterAction(plain, true, true, false), Action::Reject);
    QCOMPARE(DropClassifier::containmentDragEnterAction(plain, false, false, false), Action::Reject);
    QCOMPARE(DropClassifier::containmentDragEnterAction(launchers, false, true, true), Action::ShowAddLaunchersMessage);
    //! launchers without a stealing applet route to the plain spacer
    QCOMPARE(DropClassifier::containmentDragEnterAction(launchers, false, true, false), Action::InsertSpacer);
    QCOMPARE(DropClassifier::containmentDragEnterAction(plain, false, true, true), Action::InsertSpacer);
}

void DropClassifierTest::containmentMoveLadder_truthTable()
{
    using Action = DropClassifier::ContainmentMoveAction;
    const DropClassifier::ContainmentDragFlags launchers{.onlyLaunchers = true};
    const DropClassifier::ContainmentDragFlags task{.isTask = true, .onlyLaunchers = true};

    //! a task drag leaves state untouched even when a stealing applet
    //! would want the launchers; move never re-checks immutability
    //! (enter already rejected) - faithful Qt5 onDragMove
    QCOMPARE(DropClassifier::containmentDragMoveAction(task, true), Action::LeaveUnchanged);
    QCOMPARE(DropClassifier::containmentDragMoveAction(launchers, true), Action::ShowAddLaunchersMessage);
    QCOMPARE(DropClassifier::containmentDragMoveAction(launchers, false), Action::InsertSpacer);
    QCOMPARE(DropClassifier::containmentDragMoveAction({}, true), Action::InsertSpacer);
}

void DropClassifierTest::containmentDropLadder_truthTable()
{
    using Action = DropClassifier::ContainmentDropAction;
    const DropClassifier::ContainmentDragFlags launchers{.onlyLaunchers = true};
    const DropClassifier::ContainmentDragFlags task{.isTask = true};

    QCOMPARE(DropClassifier::containmentDropAction(task, true, true), Action::Ignore);
    QCOMPARE(DropClassifier::containmentDropAction(launchers, false, true), Action::Ignore);
    QCOMPARE(DropClassifier::containmentDropAction(launchers, true, true), Action::AddLaunchersToStealingApplet);
    QCOMPARE(DropClassifier::containmentDropAction(launchers, true, false), Action::ProcessMime);
    QCOMPARE(DropClassifier::containmentDropAction({}, true, true), Action::ProcessMime);
}

void DropClassifierTest::tasksDropLadder_truthTable()
{
    using Action = DropClassifier::TasksDropAction;

    QCOMPARE(DropClassifier::tasksDropAction({}), Action::Ignore);
    QCOMPARE(DropClassifier::tasksDropAction({.droppingSeparator = true}), Action::AddSeparator);
    //! separator wins over files when a drag carries both (reachable:
    //! a separator payload that also has non-application urls)
    QCOMPARE(DropClassifier::tasksDropAction({.droppingSeparator = true, .droppingFiles = true}), Action::AddSeparator);
    QCOMPARE(DropClassifier::tasksDropAction({.droppingOnlyLaunchers = true}), Action::DropUrls);
    QCOMPARE(DropClassifier::tasksDropAction({.droppingFiles = true}), Action::DropUrls);
    //! an internal task move released over the area: accepted at enter,
    //! deliberately does nothing at drop ("Reject internal drops")
    QCOMPARE(DropClassifier::tasksDropAction({.movingTask = true}), Action::LeaveUnchanged);
    //! movingTask + files (a task drag carrying urls): the files route
    //! fires, because the Qt5 else-if chain checked separator/launchers/
    //! files before falling through to the internal-move no-op
    QCOMPARE(DropClassifier::tasksDropAction({.movingTask = true, .droppingFiles = true}), Action::DropUrls);

    QVERIFY(!DropClassifier::tasksDragAccepts({}));
    QVERIFY(DropClassifier::tasksDragAccepts({.movingTask = true}));
    QVERIFY(DropClassifier::tasksDragAccepts({.droppingFiles = true}));
}

void DropClassifierTest::separatorDropPosition_hoveredOrRowHead()
{
    QCOMPARE(DropClassifier::separatorDropPosition(5), 5);
    QCOMPARE(DropClassifier::separatorDropPosition(0), 0);
    //! hovered but unindexed collapses to the row head, exactly like no
    //! hovered item at all (Qt5's `itemIndex >= 0` ternary)
    QCOMPARE(DropClassifier::separatorDropPosition(-1), 0);
    QCOMPARE(DropClassifier::separatorDropPosition(std::nullopt), 0);
}

void DropClassifierTest::insertIndexAt_table_data()
{
    QTest::addColumn<bool>("hasAbove");
    QTest::addColumn<int>("aboveIndex");
    QTest::addColumn<QPointF>("pos");
    QTest::addColumn<bool>("vertical");
    QTest::addColumn<qreal>("step");
    QTest::addColumn<int>("expected");

    QTest::newRow("hovered item wins regardless of position")
            << true << 5 << QPointF(3.0, 0.0) << false << 24.0 << 5;
    //! JS truthiness quirk: index 0 is falsy, falls to the stripe math -
    //! which answers 0 anywhere inside the first step, so the quirk only
    //! shows at the exact row origin
    QTest::newRow("hovered index 0 inside first step -> stripe answers 0")
            << true << 0 << QPointF(10.0, 0.0) << false << 24.0 << 0;
    QTest::newRow("hovered index 0 at exact origin -> -1 (pinned quirk)")
            << true << 0 << QPointF(0.0, 0.0) << false << 24.0 << -1;
    //! a transient -1 is truthy in JS and returned as-is; TasksModel::
    //! move rejects it downstream
    QTest::newRow("transient hovered index -1 returned as-is")
            << true << -1 << QPointF(100.0, 0.0) << false << 24.0 << -1;
    QTest::newRow("no hovered item: stripe math")
            << false << 0 << QPointF(100.0, 0.0) << false << 24.0 << 4;
    //! ceil boundary: an exact multiple lands on the previous stripe
    QTest::newRow("exact step boundary")
            << false << 0 << QPointF(48.0, 0.0) << false << 24.0 << 1;
    QTest::newRow("just past the boundary")
            << false << 0 << QPointF(48.1, 0.0) << false << 24.0 << 2;
    QTest::newRow("vertical dock reads y")
            << false << 0 << QPointF(500.0, 30.0) << true << 24.0 << 1;
    //! mapToItem hands negative coordinates before the target origin;
    //! the negative answers are inert downstream (move() rejects) and
    //! deliberately NOT clamped
    QTest::newRow("before the target origin")
            << false << 0 << QPointF(-50.0, 0.0) << false << 24.0 << -3;
}

void DropClassifierTest::insertIndexAt_table()
{
    QFETCH(bool, hasAbove);
    QFETCH(int, aboveIndex);
    QFETCH(QPointF, pos);
    QFETCH(bool, vertical);
    QFETCH(qreal, step);
    QFETCH(int, expected);

    const std::optional<int> above = hasAbove ? std::optional<int>{aboveIndex} : std::nullopt;
    const Qt::Orientation orientation = vertical ? Qt::Vertical : Qt::Horizontal;

    QCOMPARE(DropClassifier::insertIndexAt(above, pos, orientation, step), expected);
}

void DropClassifierTest::dragMoveRouting_table_data()
{
    using Snapshot = DropClassifier::TasksDragMoveSnapshot;
    using Action = DropClassifier::TasksDragMoveAction;

    QTest::addColumn<Snapshot>("snapshot");
    QTest::addColumn<Action>("expected");

    const auto internalDrag = [](int index, bool isLauncher, bool isAbove) {
        return std::optional<DropClassifier::DragSourceState>{
            DropClassifier::DragSourceState{.itemIndex = index, .isLauncher = isLauncher, .isAbove = isAbove}};
    };
    const auto item = [](int index, bool isLauncher) {
        return std::optional<DropClassifier::AboveItemState>{
            DropClassifier::AboveItemState{.itemIndex = index, .hasModelData = true, .isLauncher = isLauncher}};
    };

    //! THE null==null quirk (pinned faithful): an external drag over
    //! empty row space with no ignored item suppresses - ClearHover is
    //! unreachable for external drags until something sets ignoredItem;
    //! hover clears on dragLeave instead
    QTest::newRow("external drag over empty space suppresses (null==null)")
            << Snapshot{.aboveIsIgnored = true, .positionInTarget = {10, 0}, .itemStep = 24}
            << Action::SuppressRepeatTarget;

    QTest::newRow("external drag still over the ignored item suppresses")
            << Snapshot{.above = item(2, false), .hasIgnoredItem = true, .aboveIsIgnored = true,
                        .positionInTarget = {50, 0}, .itemStep = 24}
            << Action::SuppressRepeatTarget;

    //! the EITM rule: a small launcher dragged across a bigger
    //! non-launcher must not re-target it twice in a row
    QTest::newRow("launcher crossing a non-launcher ignored item suppresses")
            << Snapshot{.dragSource = internalDrag(1, true, false), .above = item(2, false),
                        .hasIgnoredItem = true, .aboveIsIgnored = true, .sortIsManual = true,
                        .positionInTarget = {50, 0}, .itemStep = 24}
            << Action::SuppressRepeatTarget;

    //! same crossing over a LAUNCHER ignored item does not suppress, but
    //! the ignore bookkeeping still blocks the reorder branch -> None
    QTest::newRow("launcher crossing a launcher ignored item idles")
            << Snapshot{.dragSource = internalDrag(1, true, false), .above = item(2, true),
                        .hasIgnoredItem = true, .aboveIsIgnored = true, .sortIsManual = true,
                        .positionInTarget = {50, 0}, .itemStep = 24}
            << Action::None;

    QTest::newRow("manual sort reorders to the hovered index")
            << Snapshot{.dragSource = internalDrag(0, false, false), .above = item(3, false),
                        .sortIsManual = true, .positionInTarget = {80, 0}, .itemStep = 24}
            << Action::ReorderDragSource;

    QTest::newRow("reorder over empty space uses the stripe math")
            << Snapshot{.dragSource = internalDrag(0, false, false),
                        //! above == ignoredItem is false: above is null, ignored... also null?
                        //! no - this row has an internal drag, branch (A) needs !dragSource;
                        //! aboveIsIgnored true (both null) is consistent AND reachable
                        .aboveIsIgnored = true, .sortIsManual = true,
                        .positionInTarget = {100, 0}, .itemStep = 24}
            << Action::ReorderDragSource;

    QTest::newRow("dropping on itself keeps order")
            << Snapshot{.dragSource = internalDrag(2, false, true), .above = item(2, false),
                        .sortIsManual = true, .positionInTarget = {60, 0}, .itemStep = 24}
            << Action::KeepOrder;

    //! insertAt resolves to the source's own index -> no move
    QTest::newRow("stripe answer equal to own index keeps order")
            << Snapshot{.dragSource = internalDrag(4, false, false), .aboveIsIgnored = true,
                        .sortIsManual = true, .positionInTarget = {100, 0}, .itemStep = 24}
            << Action::KeepOrder;

    //! ignore bookkeeping present: the reorder branch is gated off and
    //! the external-drag branches skip an internal drag -> None
    QTest::newRow("internal drag with ignore bookkeeping idles")
            << Snapshot{.dragSource = internalDrag(0, false, false), .above = item(3, false),
                        .hasIgnoredItem = true, .sortIsManual = true,
                        .positionInTarget = {80, 0}, .itemStep = 24}
            << Action::None;

    QTest::newRow("non-manual sort never reorders")
            << Snapshot{.dragSource = internalDrag(0, false, false), .above = item(3, false),
                        .positionInTarget = {80, 0}, .itemStep = 24}
            << Action::None;

    QTest::newRow("external drag entering a new item hovers it")
            << Snapshot{.above = item(2, false), .positionInTarget = {50, 0}, .itemStep = 24}
            << Action::HoverAbove;

    QTest::newRow("external drag still over the hovered item idles")
            << Snapshot{.above = item(2, false), .aboveIsHovered = true,
                        .positionInTarget = {50, 0}, .itemStep = 24}
            << Action::None;

    //! the one reachable ClearHover: an ignored item still recorded
    //! (dragSource just cleared mid-gesture) while the pointer sits over
    //! empty space that is NOT the ignored item
    QTest::newRow("stale ignore bookkeeping over empty space clears hover")
            << Snapshot{.hasIgnoredItem = true, .positionInTarget = {10, 0}, .itemStep = 24}
            << Action::ClearHover;
}

void DropClassifierTest::dragMoveRouting_table()
{
    QFETCH(DropClassifier::TasksDragMoveSnapshot, snapshot);
    QFETCH(DropClassifier::TasksDragMoveAction, expected);

    const auto decision = DropClassifier::decideTasksDragMove(snapshot);
    QCOMPARE(decision.action, expected);

    //! the decision invariant: a target index travels with a reorder
    //! and only with a reorder
    QCOMPARE(decision.moveTo.has_value(), expected == DropClassifier::TasksDragMoveAction::ReorderDragSource);
}

void DropClassifierTest::dragMoveRouting_reorderAlwaysCarriesTarget()
{
    //! hovered reorder carries the hovered index; empty-space reorder
    //! carries the stripe answer
    const DropClassifier::TasksDragMoveSnapshot hovered{
        .dragSource = DropClassifier::DragSourceState{.itemIndex = 0},
        .above = DropClassifier::AboveItemState{.itemIndex = 3, .hasModelData = true},
        .sortIsManual = true, .positionInTarget = {80, 0}, .itemStep = 24};
    const auto hoveredMove = DropClassifier::decideTasksDragMove(hovered).moveTo;
    QVERIFY(hoveredMove.has_value());
    QCOMPARE(*hoveredMove, 3);

    const DropClassifier::TasksDragMoveSnapshot empty{
        .dragSource = DropClassifier::DragSourceState{.itemIndex = 0},
        .aboveIsIgnored = true, .sortIsManual = true,
        .positionInTarget = {100, 0}, .itemStep = 24};
    //! ceil(100/24)-1 == 4
    const auto emptyMove = DropClassifier::decideTasksDragMove(empty).moveTo;
    QVERIFY(emptyMove.has_value());
    QCOMPARE(*emptyMove, 4);
}

void DropClassifierTest::wrapper_classifiesRealMimeData()
{
    DropClassifierTools tools;
    QJSEngine engine;
    const QJSValue isApplication = engine.evaluate(
        QStringLiteral("(function(url) { return url.indexOf('.desktop') >= 0; })"));
    QVERIFY(isApplication.isCallable());

    //! a separator drag exactly as the widget explorer builds it
    QMimeData separatorMime;
    separatorMime.setData(QString(DropClassifier::PlasmoidServiceNameFormat),
                          QByteArrayLiteral("org.kde.latte.separator"));

    const QVariantMap containment = tools.classifyContainmentDrag(&separatorMime, isApplication);
    QCOMPARE(containment.value(QStringLiteral("isSeparator")).toBool(), true);
    QCOMPARE(containment.value(QStringLiteral("isPlasmoid")).toBool(), true);
    QCOMPARE(containment.value(QStringLiteral("isTask")).toBool(), false);
    QCOMPARE(containment.value(QStringLiteral("onlyLaunchers")).toBool(), false);

    const QVariantMap tasks = tools.classifyTasksDrag(&separatorMime, isApplication);
    QCOMPARE(tasks.value(QStringLiteral("droppingSeparator")).toBool(), true);
    QCOMPARE(tasks.value(QStringLiteral("movingTask")).toBool(), false);
    QCOMPARE(tasks.value(QStringLiteral("droppingFiles")).toBool(), false);

    //! a launcher-file drag: the predicate must actually be consulted
    QMimeData launcherMime;
    launcherMime.setUrls({QUrl(QStringLiteral("file:///usr/share/applications/kate.desktop"))});

    const QVariantMap launcherFlags = tools.classifyTasksDrag(&launcherMime, isApplication);
    QCOMPARE(launcherFlags.value(QStringLiteral("droppingOnlyLaunchers")).toBool(), true);
    QCOMPARE(launcherFlags.value(QStringLiteral("droppingFiles")).toBool(), false);

    QMimeData documentMime;
    documentMime.setUrls({QUrl(QStringLiteral("file:///home/notes.txt"))});

    const QVariantMap documentFlags = tools.classifyTasksDrag(&documentMime, isApplication);
    QCOMPARE(documentFlags.value(QStringLiteral("droppingOnlyLaunchers")).toBool(), false);
    QCOMPARE(documentFlags.value(QStringLiteral("droppingFiles")).toBool(), true);
}

void DropClassifierTest::wrapper_predicateExceptionIsSurfacedNotSwallowed()
{
    DropClassifierTools tools;
    QJSEngine engine;
    const QJSValue throwing = engine.evaluate(
        QStringLiteral("(function(url) { throw new Error('backend gone'); })"));
    QVERIFY(throwing.isCallable());

    QMimeData mime;
    mime.setUrls({QUrl(QStringLiteral("file:///usr/share/applications/kate.desktop"))});

    //! the throw is warned about and the url answers "not an
    //! application": the drag degrades to a files drop, never a silent
    //! misroute
    QTest::ignoreMessage(QtWarningMsg, QRegularExpression(QStringLiteral("isApplication predicate threw")));
    const QVariantMap flags = tools.classifyTasksDrag(&mime, throwing);
    QCOMPARE(flags.value(QStringLiteral("droppingOnlyLaunchers")).toBool(), false);
    QCOMPARE(flags.value(QStringLiteral("droppingFiles")).toBool(), true);
}

void DropClassifierTest::wrapper_refusesNullMimeData()
{
    DropClassifierTools tools;
    QJSEngine engine;
    const QJSValue isApplication = engine.evaluate(QStringLiteral("(function(url) { return true; })"));

    QTest::ignoreMessage(QtCriticalMsg, QRegularExpression(QStringLiteral("null mimeData")));
    const QVariantMap containment = tools.classifyContainmentDrag(nullptr, isApplication);
    QCOMPARE(containment.value(QStringLiteral("isTask")).toBool(), false);
    QCOMPARE(containment.value(QStringLiteral("onlyLaunchers")).toBool(), false);

    QTest::ignoreMessage(QtCriticalMsg, QRegularExpression(QStringLiteral("null mimeData")));
    const QVariantMap tasks = tools.classifyTasksDrag(nullptr, isApplication);
    QCOMPARE(tasks.value(QStringLiteral("movingTask")).toBool(), false);
    QCOMPARE(tasks.value(QStringLiteral("droppingFiles")).toBool(), false);
}

void DropClassifierTest::wrapper_refusesNonCallablePredicate()
{
    DropClassifierTools tools;

    QMimeData mime;
    mime.setData(QString(DropClassifier::TaskButtonItemFormat), QByteArrayLiteral("x"));

    QTest::ignoreMessage(QtCriticalMsg, QRegularExpression(QStringLiteral("callable isApplication")));
    const QVariantMap flags = tools.classifyContainmentDrag(&mime, QJSValue());
    //! the inert answer is all-false even where the mime alone would
    //! have said isTask - a refusal is a refusal, not a partial answer
    QCOMPARE(flags.value(QStringLiteral("isTask")).toBool(), false);
}

void DropClassifierTest::wrapper_decidesDragMoveFromSnapshotMap()
{
    DropClassifierTools tools;

    const QVariantMap decision = tools.decideTasksDragMove(QVariantMap{
        {QStringLiteral("dragSource"), QVariantMap{{QStringLiteral("itemIndex"), 0},
                                                   {QStringLiteral("isLauncher"), false},
                                                   {QStringLiteral("isAbove"), false}}},
        {QStringLiteral("above"), QVariantMap{{QStringLiteral("itemIndex"), 3},
                                              {QStringLiteral("hasModelData"), true},
                                              {QStringLiteral("isLauncher"), false}}},
        {QStringLiteral("hasIgnoredItem"), false},
        {QStringLiteral("aboveIsIgnored"), false},
        {QStringLiteral("aboveIsHovered"), false},
        {QStringLiteral("sortIsManual"), true},
        {QStringLiteral("posX"), 80.0},
        {QStringLiteral("posY"), 0.0},
        {QStringLiteral("vertical"), false},
        {QStringLiteral("itemStep"), 24.0},
    });

    QCOMPARE(decision.value(QStringLiteral("action")).toInt(), int(DropClassifierTools::MoveTaskReorder));
    QCOMPARE(decision.value(QStringLiteral("moveTo")).toInt(), 3);

    //! external null spellings route through the same boundary
    const QVariantMap hover = tools.decideTasksDragMove(QVariantMap{
        {QStringLiteral("dragSource"), QVariant::fromValue(nullptr)},
        {QStringLiteral("above"), QVariantMap{{QStringLiteral("itemIndex"), 2},
                                              {QStringLiteral("hasModelData"), true},
                                              {QStringLiteral("isLauncher"), true}}},
        {QStringLiteral("hasIgnoredItem"), false},
        {QStringLiteral("aboveIsIgnored"), false},
        {QStringLiteral("aboveIsHovered"), false},
        {QStringLiteral("sortIsManual"), true},
        {QStringLiteral("posX"), 50.0},
        {QStringLiteral("posY"), 0.0},
        {QStringLiteral("vertical"), false},
        {QStringLiteral("itemStep"), 24.0},
    });

    QCOMPARE(hover.value(QStringLiteral("action")).toInt(), int(DropClassifierTools::MoveTaskHoverAbove));
    QVERIFY(!hover.contains(QStringLiteral("moveTo")));
}

void DropClassifierTest::wrapper_refusesMalformedDragMoveSnapshots_data()
{
    QTest::addColumn<QVariantMap>("snapshot");

    QVariantMap valid{
        {QStringLiteral("dragSource"), QVariant::fromValue(nullptr)},
        {QStringLiteral("above"), QVariant::fromValue(nullptr)},
        {QStringLiteral("hasIgnoredItem"), false},
        {QStringLiteral("aboveIsIgnored"), true},
        {QStringLiteral("aboveIsHovered"), false},
        {QStringLiteral("sortIsManual"), false},
        {QStringLiteral("posX"), 10.0},
        {QStringLiteral("posY"), 0.0},
        {QStringLiteral("vertical"), false},
        {QStringLiteral("itemStep"), 24.0},
    };

    QVariantMap missingAbove = valid;
    missingAbove.remove(QStringLiteral("above"));
    QTest::newRow("missing above key") << missingAbove;

    QVariantMap missingScalar = valid;
    missingScalar.remove(QStringLiteral("sortIsManual"));
    QTest::newRow("missing scalar key") << missingScalar;

    QVariantMap mistypedScalar = valid;
    mistypedScalar.insert(QStringLiteral("aboveIsIgnored"), QStringLiteral("yes"));
    QTest::newRow("mistyped bool") << mistypedScalar;

    QVariantMap wrongSourceType = valid;
    wrongSourceType.insert(QStringLiteral("dragSource"), 7);
    QTest::newRow("dragSource of wrong type") << wrongSourceType;

    QVariantMap fractionalIndex = valid;
    fractionalIndex.insert(QStringLiteral("above"),
                           QVariantMap{{QStringLiteral("itemIndex"), 2.5},
                                       {QStringLiteral("hasModelData"), true},
                                       {QStringLiteral("isLauncher"), false}});
    QTest::newRow("fractional itemIndex") << fractionalIndex;

    QVariantMap zeroStep = valid;
    zeroStep.insert(QStringLiteral("itemStep"), 0.0);
    QTest::newRow("torn-down metrics (itemStep 0)") << zeroStep;

    QVariantMap inconsistentIdentity = valid;
    inconsistentIdentity.insert(QStringLiteral("aboveIsIgnored"), false);
    //! above and ignoredItem both absent MUST compare equal (JS null==null)
    QTest::newRow("identity flags inconsistent with absences") << inconsistentIdentity;
}

void DropClassifierTest::wrapper_refusesMalformedDragMoveSnapshots()
{
    QFETCH(QVariantMap, snapshot);

    DropClassifierTools tools;

    QTest::ignoreMessage(QtCriticalMsg, QRegularExpression(QStringLiteral("decideTasksDragMove snapshot is malformed")));
    const QVariantMap decision = tools.decideTasksDragMove(snapshot);

    //! the inert answer: route nothing
    QCOMPARE(decision.value(QStringLiteral("action")).toInt(), int(DropClassifierTools::MoveTaskNone));
    QVERIFY(!decision.contains(QStringLiteral("moveTo")));
}

void DropClassifierTest::wrapper_separatorDropPosition()
{
    DropClassifierTools tools;

    QCOMPARE(tools.separatorDropPosition(true, 5), 5);
    QCOMPARE(tools.separatorDropPosition(true, -1), 0);
    QCOMPARE(tools.separatorDropPosition(false, 7), 0);
}

QTEST_GUILESS_MAIN(DropClassifierTest)
#include "dropclassifiertest.moc"
