/*
    SPDX-FileCopyrightText: 2026 Bree Spektor
    SPDX-FileCopyrightText: 2026 Latte Dock contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

// EX-18 LengthOffsetClamp (docs/tracking/QML_EXTRACTION_PLAN.md): the mutual
// maxLength/minLength/offset clamp that keeps a dock on-screen, dedup'd
// out of the two Qt5-inherited QML copies (the canvas maxLength ruler and
// the Appearance page's slider cluster). Divergence between those copies
// was a config-corruption class: both edit the same three config keys.
//
// Expected slider-specific values are hand-derived from the shipped QML bodies
// at the extraction commit (verified byte-identical in math to their f0ad7b23
// Qt5 ancestors; docs/agent-logs/EX-18.md has the arbitration record). The
// final placement transaction deliberately replaces Qt5's alignment-change
// bypass and out-of-domain multi-step healing; placementstate.h records both
// the root invariant and the deviation. No row was generated by running the
// header under test.
//
// The one deliberate deviation (recorded in the spec and the agent log):
// the page slider's off-screen correction runs on the EFFECTIVE (floored)
// maxLength where Qt5 used the raw slider value; the two disagree only in
// a state the slider wiring makes unreachable, and the raw form breaks
// the on-screen guarantee and idempotence the spec's test plan demands.
// toValue_correctionUsesEffectiveMaxLength pins the fixed behavior with
// the counterexample.

#include <QtTest>

// Qt
#include <QRegularExpression>

// C++
#include <cmath>
#include <limits>
#include <type_traits>

#include "../../app/settings/lengthoffsetclamp.h"
#include "../../app/settings/lengthoffsetclampbridge.h"

using namespace Latte::Settings::LengthOffsetClamp;

// invalid states designed out (step-2.5 law), compile-time proof where
// the language can carry it: the state is three plain percent values -
// no sentinel member, nothing optional to misread
static_assert(std::is_aggregate_v<LengthState> && std::is_aggregate_v<OffsetBounds>
                  && std::is_aggregate_v<OffsetClamp>,
              "clamp value types stay plain aggregates; behavior lives in the free functions");

class LengthOffsetClampTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    // the deduplicated off-screen correction (the block that existed twice)
    void pullOffsetOnScreen_table_data();
    void pullOffsetOnScreen_table();
    void pullOffsetOnScreen_neverTouchesMinLength();

    // ruler wheel entry point
    void clampMaxLengthByStep_table_data();
    void clampMaxLengthByStep_table();
    void byStep_couplingWalksBothRailsDown();

    // page slider entry point
    void clampMaxLengthToValue_table_data();
    void clampMaxLengthToValue_table();
    void toValue_correctionUsesEffectiveMaxLength();
    void toValue_maxNeverEndsBelowMin();

    // D17: the Maximum floor is alignment-aware - Justify has no minLength floor
    void toValue_justifyHonoursRequestBelowStoredMinimum();
    void byStep_justifyIgnoresStoredMinimumFloorButKeepsTheRail();

    // offset slider bounds (fromValue/toValue/screenLengthMaxFactor)
    void offsetSliderBounds_table_data();
    void offsetSliderBounds_table();

    // offset slider entry point
    void clampOffset_table_data();
    void clampOffset_table();
    void clampOffset_neverShrinksMaxLengthInSaneDomain();
    void clampOffset_outOfRangeMaxLengthSelfHeals();

    // class invariants over input grids
    void invariants_afterByStep_gridSweep();
    void invariants_afterToValue_gridSweep();
    void idempotence_byStepZeroIsIdentityOnClampedStates();
    void idempotence_toValueReapplyIsIdentity();
    void idempotence_clampOffsetReapplyIsIdentity();
    void crossedUpdates_convergeOnScreenWithMinBelowMax();
    void rulerThenSlider_truncationDisagreementIsPinned();

    // the QML boundary (bridge compiled into this binary, sanitized)
    void bridge_mapsAlignmentTotally();
    void bridge_mapsJustifyToItsOwnFloor();
    void bridge_resultsMatchCore();
    void bridge_refusesNonFiniteLoudly();
};

namespace {

constexpr double kEps = 1e-9;

//! the post-condition both QML copies existed to enforce: the dock stays
//! fully on-screen (total length within the screen, and for centered
//! alignments the offset never pushes either half past the screen middle)
bool staysOnScreen(double maxLength, double offset, Alignment alignment)
{
    if (std::fabs(offset) + maxLength > 100.0 + kEps) {
        return false;
    }
    if (alignment == Alignment::Centered
        && std::fabs(offset) + maxLength / 2.0 > 50.0 + kEps) {
        return false;
    }
    return true;
}

} // namespace

void LengthOffsetClampTest::pullOffsetOnScreen_table_data()
{
    QTest::addColumn<bool>("centered");
    QTest::addColumn<double>("maxLength");
    QTest::addColumn<double>("offset");
    QTest::addColumn<double>("expectedOffset");

    // centered: |offset| + max > 100 overflow pulls offset back
    QTest::newRow("C full-length offset collapses to 0") << true << 100.0 << 10.0 << 0.0;
    QTest::newRow("C overflow suggests then halves") << true << 80.0 << 30.0 << 10.0;
    QTest::newRow("C overflow negative mirror") << true << 80.0 << -30.0 << -10.0;
    QTest::newRow("C halfway rule catches the suggestion") << true << 60.0 << 25.0 << 20.0;
    QTest::newRow("C small negative overflow") << true << 90.0 << -20.0 << -5.0;
    // centeredCheck fires where the total check cannot (total == 100)
    QTest::newRow("C total exactly 100 still recenters") << true << 80.0 << 20.0 << 10.0;
    QTest::newRow("C below-total centered spill") << true << 30.0 << 40.0 << 35.0;
    // no-fire rows: strict inequalities
    QTest::newRow("C exactly at the half boundary keeps offset") << true << 80.0 << 10.0 << 10.0;
    QTest::newRow("C comfortably on-screen keeps offset") << true << 40.0 << 20.0 << 20.0;
    QTest::newRow("C zero offset at full length keeps 0") << true << 100.0 << 0.0 << 0.0;

    // edge alignments: only the total check exists, offset floor is 0
    QTest::newRow("E overflow pulls to the remainder") << false << 80.0 << 30.0 << 20.0;
    QTest::newRow("E full length pulls to 0") << false << 100.0 << 30.0 << 0.0;
    QTest::newRow("E large offset small dock") << false << 30.0 << 75.0 << 70.0;
    QTest::newRow("E on-screen untouched") << false << 80.0 << 15.0 << 15.0;
    QTest::newRow("E total exactly 100 untouched") << false << 80.0 << 20.0 << 20.0;
    // A centered negative offset cannot survive an edge-alignment transition:
    // edge offsets are inward distances and therefore floor at zero.
    QTest::newRow("E negative centered offset floors at the edge") << false << 80.0 << -30.0 << 0.0;
}

void LengthOffsetClampTest::pullOffsetOnScreen_table()
{
    QFETCH(bool, centered);
    QFETCH(double, maxLength);
    QFETCH(double, offset);
    QFETCH(double, expectedOffset);

    const Alignment alignment = centered ? Alignment::Centered : Alignment::Edge;
    const LengthState result = pullOffsetOnScreen({maxLength, 30.0, offset}, alignment);

    QCOMPARE(result.offset, expectedOffset);
    QCOMPARE(result.maxLength, maxLength);   // this correction never resizes
    QVERIFY(staysOnScreen(result.maxLength, result.offset, alignment));
}

void LengthOffsetClampTest::pullOffsetOnScreen_neverTouchesMinLength()
{
    for (const double min : {0.0, 30.0, 77.5, 100.0}) {
        const LengthState result = pullOffsetOnScreen({80.0, min, 30.0}, Alignment::Centered);
        QCOMPARE(result.minLength, min);
    }
}

void LengthOffsetClampTest::clampMaxLengthByStep_table_data()
{
    QTest::addColumn<bool>("centered");
    QTest::addColumn<double>("maxLength");
    QTest::addColumn<double>("minLength");
    QTest::addColumn<double>("offset");
    QTest::addColumn<double>("step");
    QTest::addColumn<double>("expectedMax");
    QTest::addColumn<double>("expectedMin");
    QTest::addColumn<double>("expectedOffset");

    // the 30..100 rails (spec slot: floor/ceiling)
    QTest::newRow("floor stops the wheel at 30") << false << 32.0 << 0.0 << 0.0 << -6.0
                                                 << 30.0 << 0.0 << 0.0;
    QTest::newRow("ceiling stops the wheel at 100") << false << 98.0 << 30.0 << 0.0 << 6.0
                                                    << 100.0 << 30.0 << 0.0;
    QTest::newRow("ceiling is idempotent for further steps") << false << 100.0 << 30.0 << 0.0 << 6.0
                                                             << 100.0 << 30.0 << 0.0;
    // an out-of-range config heals through the rail instead of refusing
    QTest::newRow("over-100 config heals to the ceiling") << false << 150.0 << 30.0 << 0.0 << 6.0
                                                          << 100.0 << 30.0 << 0.0;

    // max == min coupling: both rails move together, both directions
    QTest::newRow("coupled pair steps down together") << false << 100.0 << 100.0 << 0.0 << -6.0
                                                      << 94.0 << 94.0 << 0.0;
    QTest::newRow("coupled pair steps up together") << false << 50.0 << 50.0 << 0.0 << 6.0
                                                    << 56.0 << 56.0 << 0.0;
    QTest::newRow("coupled pair lands on the floor") << false << 32.0 << 32.0 << 0.0 << -6.0
                                                     << 30.0 << 30.0 << 0.0;
    // uncoupled: minLength is a floor the wheel cannot cross
    QTest::newRow("min floor catches a downward step") << false << 45.0 << 40.0 << 0.0 << -6.0
                                                       << 40.0 << 40.0 << 0.0;

    // growth spills into the off-screen correction (spec slot: overflow)
    QTest::newRow("C growth recenters the offset") << true << 96.0 << 30.0 << 20.0 << 6.0
                                                   << 100.0 << 30.0 << 0.0;
    QTest::newRow("C growth halves a spilled suggestion") << true << 74.0 << 30.0 << 40.0 << 6.0
                                                          << 80.0 << 30.0 << 10.0;
    QTest::newRow("C negative offset mirror") << true << 74.0 << 30.0 << -40.0 << 6.0
                                              << 80.0 << 30.0 << -10.0;
    QTest::newRow("E growth pushes offset to the remainder") << false << 50.0 << 30.0 << 60.0 << 6.0
                                                             << 56.0 << 30.0 << 44.0;
}

void LengthOffsetClampTest::clampMaxLengthByStep_table()
{
    QFETCH(bool, centered);
    QFETCH(double, maxLength);
    QFETCH(double, minLength);
    QFETCH(double, offset);
    QFETCH(double, step);
    QFETCH(double, expectedMax);
    QFETCH(double, expectedMin);
    QFETCH(double, expectedOffset);

    const Alignment alignment = centered ? Alignment::Centered : Alignment::Edge;
    const LengthState result = clampMaxLengthByStep({maxLength, minLength, offset}, step, alignment);

    QCOMPARE(result.maxLength, expectedMax);
    QCOMPARE(result.minLength, expectedMin);
    QCOMPARE(result.offset, expectedOffset);
}

void LengthOffsetClampTest::byStep_couplingWalksBothRailsDown()
{
    // caught on paper while reading the ruler body: an uncoupled pair
    // becomes coupled the moment the min floor catches the wheel, and
    // from then on both rails walk down together to the 30 floor
    LengthState state{45.0, 40.0, 0.0};

    state = clampMaxLengthByStep(state, -6.0, Alignment::Edge);
    QCOMPARE(state.maxLength, 40.0);   // floor caught it, now coupled
    QCOMPARE(state.minLength, 40.0);

    state = clampMaxLengthByStep(state, -6.0, Alignment::Edge);
    QCOMPARE(state.maxLength, 34.0);   // coupled walk
    QCOMPARE(state.minLength, 34.0);

    state = clampMaxLengthByStep(state, -6.0, Alignment::Edge);
    QCOMPARE(state.maxLength, 30.0);   // both stop on the rail
    QCOMPARE(state.minLength, 30.0);

    state = clampMaxLengthByStep(state, -6.0, Alignment::Edge);
    QCOMPARE(state.maxLength, 30.0);   // and stay there
    QCOMPARE(state.minLength, 30.0);
}

void LengthOffsetClampTest::clampMaxLengthToValue_table_data()
{
    QTest::addColumn<bool>("centered");
    QTest::addColumn<double>("requested");
    QTest::addColumn<double>("minLength");
    QTest::addColumn<double>("offset");
    QTest::addColumn<double>("expectedMax");
    QTest::addColumn<double>("expectedOffset");

    QTest::newRow("plain request passes through") << false << 80.0 << 30.0 << 0.0
                                                  << 80.0 << 0.0;
    QTest::newRow("min floor lifts a low request") << false << 20.0 << 50.0 << 0.0
                                                   << 50.0 << 0.0;
    QTest::newRow("localMinValue floor lifts zero") << false << 0.0 << 0.0 << 0.0
                                                    << 1.0 << 0.0;
    QTest::newRow("E overflow pulls offset back") << false << 90.0 << 30.0 << 30.0
                                                  << 90.0 << 10.0;
    QTest::newRow("C spill halves the suggestion") << true << 95.0 << 30.0 << 5.0
                                                   << 95.0 << 2.5;
    QTest::newRow("full pair keeps its offset") << false << 100.0 << 100.0 << 0.0
                                                << 100.0 << 0.0;
}

void LengthOffsetClampTest::clampMaxLengthToValue_table()
{
    QFETCH(bool, centered);
    QFETCH(double, requested);
    QFETCH(double, minLength);
    QFETCH(double, offset);
    QFETCH(double, expectedMax);
    QFETCH(double, expectedOffset);

    const Alignment alignment = centered ? Alignment::Centered : Alignment::Edge;
    const LengthState result = clampMaxLengthToValue(requested, minLength, offset, alignment);

    QCOMPARE(result.maxLength, expectedMax);
    QCOMPARE(result.minLength, minLength);   // this path never edits the min
    QCOMPARE(result.offset, expectedOffset);
}

void LengthOffsetClampTest::toValue_correctionUsesEffectiveMaxLength()
{
    // the recorded deviation from Qt5, with its counterexample. Qt5 wrote
    // maxLength = max(value, minLength, 1) but ran the off-screen
    // correction on the raw value. For {value=0, min=0, offset=60,
    // Centered} that computes suggested = max(0, 100-0) = 100, then the
    // halving rule gives 50 - 0/2 = 50: offset 50 with maxLength 1 is
    // still off-screen (50 + 0.5 > 50) and a second application moves it
    // again (non-idempotent). Correcting from the effective maxLength
    // gives 49.5, on-screen and stable. The state is unreachable through
    // the slider (its pressed-branch snaps value up to the floor first),
    // so live behavior is unchanged.
    const LengthState result = clampMaxLengthToValue(0.0, 0.0, 60.0, Alignment::Centered);

    QCOMPARE(result.maxLength, 1.0);
    QCOMPARE(result.offset, 49.5);
    QVERIFY(staysOnScreen(result.maxLength, result.offset, Alignment::Centered));

    const LengthState again = clampMaxLengthToValue(result.maxLength, result.minLength,
                                                    result.offset, Alignment::Centered);
    QCOMPARE(again.maxLength, result.maxLength);
    QCOMPARE(again.offset, result.offset);
}

void LengthOffsetClampTest::toValue_maxNeverEndsBelowMin()
{
    // pins the proof that made the page's trailing
    // `if (maxLength < minLength) minLengthSlider.updateMinLength()`
    // deletable as dead code: the floor includes minLength, so the
    // condition could never hold (dead since Qt5, same body at f0ad7b23)
    for (const double requested : {-5.0, 0.0, 0.5, 1.0, 20.0, 50.0, 79.9, 100.0}) {
        for (const double min : {0.0, 29.0, 30.0, 50.0, 77.5, 100.0}) {
            const LengthState result = clampMaxLengthToValue(requested, min, 0.0, Alignment::Edge);
            QVERIFY2(result.maxLength >= result.minLength,
                     qPrintable(QStringLiteral("req=%1 min=%2 -> max=%3")
                                    .arg(requested).arg(min).arg(result.maxLength)));
        }
    }
}

void LengthOffsetClampTest::toValue_justifyHonoursRequestBelowStoredMinimum()
{
    // D17: a Justify dock's Minimum slider is disabled, so a stale stored
    // minLength must NOT floor its Maximum. The same request under Edge and
    // Center IS floored (the floor stays alignment-aware, not removed).
    //
    // DEVIATION from Qt5, recorded: Qt5 floored Maximum by minLength for
    // every alignment (latte-dock-qt6 AppearanceConfig.qml:274), so a Justify
    // dock there was stranded above a frozen minLength. This port diverges
    // deliberately (lengthoffsetclamp.h maximumIsFlooredByMinimum).
    const LengthState justify = clampMaxLengthToValue(40.0, 50.0, 0.0, Alignment::Justify);
    QCOMPARE(justify.maxLength, 40.0);        // honoured: 40 < stored min 50
    QCOMPARE(justify.minLength, 50.0);        // this path never edits the min

    const LengthState edge = clampMaxLengthToValue(40.0, 50.0, 0.0, Alignment::Edge);
    QCOMPARE(edge.maxLength, 50.0);           // still floored by the stored min

    const LengthState centered = clampMaxLengthToValue(40.0, 50.0, 0.0, Alignment::Centered);
    QCOMPARE(centered.maxLength, 50.0);       // Center keeps the floor too

    // the localMinValue floor of 1 is NOT alignment-specific: even Justify
    // cannot go to zero length
    const LengthState justifyZero = clampMaxLengthToValue(0.0, 50.0, 0.0, Alignment::Justify);
    QCOMPARE(justifyZero.maxLength, 1.0);
}

void LengthOffsetClampTest::byStep_justifyIgnoresStoredMinimumFloorButKeepsTheRail()
{
    // the ruler path skips the stored-min floor under Justify too, so a wheel
    // step can carry Maximum below a frozen minLength...
    const LengthState justify = clampMaxLengthByStep({52.0, 50.0, 0.0}, -6.0, Alignment::Justify);
    QCOMPARE(justify.maxLength, 46.0);        // 52 - 6, not floored up to 50
    QCOMPARE(justify.minLength, 50.0);        // uncoupled, the min is untouched

    // ...while an Edge step is still caught by the stored-min floor
    const LengthState edge = clampMaxLengthByStep({52.0, 50.0, 0.0}, -6.0, Alignment::Edge);
    QCOMPARE(edge.maxLength, 50.0);

    // the 30..100 ruler rail is alignment-independent: Justify still cannot
    // cross 30, only the stored-min floor is skipped
    const LengthState justifyRail = clampMaxLengthByStep({33.0, 80.0, 0.0}, -6.0, Alignment::Justify);
    QCOMPARE(justifyRail.maxLength, 30.0);
}

void LengthOffsetClampTest::offsetSliderBounds_table_data()
{
    QTest::addColumn<bool>("centered");
    QTest::addColumn<double>("maxLength");
    QTest::addColumn<double>("expectedFrom");
    QTest::addColumn<double>("expectedTo");

    // spec slot: edge alignments get [0, 2*factor], centered get
    // [-factor, factor] - the bounds differ, the reachable width matches
    QTest::newRow("C full length pins to zero") << true << 100.0 << 0.0 << 0.0;
    QTest::newRow("E full length pins to zero") << false << 100.0 << 0.0 << 0.0;
    QTest::newRow("C zero length spans the middle") << true << 0.0 << -50.0 << 50.0;
    QTest::newRow("E zero length spans the screen") << false << 0.0 << 0.0 << 100.0;
    QTest::newRow("C mid length") << true << 30.0 << -35.0 << 35.0;
    QTest::newRow("E mid length") << false << 30.0 << 0.0 << 70.0;

    // truncation rows: the shipped slider computed the factor through a
    // `property int`, and QML int bindings truncate toward zero (probed
    // on the pinned qtdeclarative 6.11.0, qmltestrunner offscreen,
    // 2026-07-16: 10.5 -> 10, -10.5 -> -10, 10.6 -> 10). qRound would
    // give 11 for the first row - these rows catch that substitution.
    QTest::newRow("C odd length truncates the half") << true << 79.0 << -10.0 << 10.0;
    QTest::newRow("E odd length truncates the half") << false << 79.0 << 0.0 << 20.0;
    QTest::newRow("C fractional length truncates") << true << 78.9 << -10.0 << 10.0;
    QTest::newRow("C fractional above truncates too") << true << 79.9 << -10.0 << 10.0;
    QTest::newRow("C fractional quarter") << true << 45.5 << -27.0 << 27.0;

    // out-of-range config: from > to, inherited Qt5 shape (the
    // composition in clampOffset defines what happens; see that test)
    QTest::newRow("C over-100 inverts the bounds") << true << 150.0 << 25.0 << -25.0;
    QTest::newRow("E over-100 inverts the bounds") << false << 150.0 << 0.0 << -50.0;
}

void LengthOffsetClampTest::offsetSliderBounds_table()
{
    QFETCH(bool, centered);
    QFETCH(double, maxLength);
    QFETCH(double, expectedFrom);
    QFETCH(double, expectedTo);

    const Alignment alignment = centered ? Alignment::Centered : Alignment::Edge;
    const OffsetBounds bounds = offsetSliderBounds(maxLength, alignment);

    QCOMPARE(bounds.from, expectedFrom);
    QCOMPARE(bounds.to, expectedTo);
}

void LengthOffsetClampTest::clampOffset_table_data()
{
    QTest::addColumn<bool>("centered");
    QTest::addColumn<double>("maxLength");
    QTest::addColumn<double>("requested");
    QTest::addColumn<double>("expectedMax");
    QTest::addColumn<double>("expectedOffset");

    QTest::newRow("C in-bounds request passes") << true << 80.0 << 5.0 << 80.0 << 5.0;
    QTest::newRow("C request beyond the truncated bound") << true << 79.0 << 10.5 << 79.0 << 10.0;
    QTest::newRow("C negative mirror") << true << 79.0 << -10.5 << 79.0 << -10.0;
    QTest::newRow("C full length forces zero") << true << 100.0 << 7.0 << 100.0 << 0.0;
    QTest::newRow("E oversized request hits the bound") << false << 80.0 << 100.0 << 80.0 << 20.0;
    QTest::newRow("E negative request floors at zero") << false << 80.0 << -5.0 << 80.0 << 0.0;
    QTest::newRow("E zero length normalizes before deriving its rail")
        << false << 0.0 << 200.0 << 1.0 << 98.0;
}

void LengthOffsetClampTest::clampOffset_table()
{
    QFETCH(bool, centered);
    QFETCH(double, maxLength);
    QFETCH(double, requested);
    QFETCH(double, expectedMax);
    QFETCH(double, expectedOffset);

    const Alignment alignment = centered ? Alignment::Centered : Alignment::Edge;
    const OffsetClamp result = clampOffset(maxLength, requested, alignment);

    QCOMPARE(result.maxLength, expectedMax);
    QCOMPARE(result.offset, expectedOffset);
    QVERIFY(staysOnScreen(result.maxLength, result.offset, alignment));
}

void LengthOffsetClampTest::clampOffset_neverShrinksMaxLengthInSaneDomain()
{
    // For maxLength in [1,100] the offset operation never shrinks maximum.
    // Zero is outside the persisted placement domain and normalizes to the
    // same 1% floor used by the Maximum slider.
    for (const double max : {0.0, 1.0, 15.0, 30.0, 45.5, 79.0, 79.9, 80.0, 99.0, 100.0}) {
        for (const double requested : {-200.0, -50.0, -10.5, 0.0, 0.1, 10.0, 49.5, 100.0, 200.0}) {
            for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                const OffsetClamp result = clampOffset(max, requested, alignment);
                QCOMPARE(result.maxLength, std::max(1.0, max));
                QVERIFY(staysOnScreen(result.maxLength, result.offset, alignment));
            }
        }
    }
}

void LengthOffsetClampTest::clampOffset_outOfRangeMaxLengthSelfHeals()
{
    // Maximum is normalized before the slider rail is derived. This prevents
    // an invalid maximum from generating inverted bounds and makes one
    // application both heal and settle.
    const OffsetClamp centered = clampOffset(150.0, 0.0, Alignment::Centered);
    QCOMPARE(centered.offset, 0.0);
    QCOMPARE(centered.maxLength, 100.0);
    QVERIFY(staysOnScreen(centered.maxLength, centered.offset, Alignment::Centered));

    const OffsetClamp centeredAgain = clampOffset(centered.maxLength, centered.offset,
                                                  Alignment::Centered);
    QCOMPARE(centeredAgain.maxLength, centered.maxLength);
    QCOMPARE(centeredAgain.offset, centered.offset);

    const OffsetClamp edge = clampOffset(150.0, 0.0, Alignment::Edge);
    QCOMPARE(edge.offset, 0.0);
    QCOMPARE(edge.maxLength, 100.0);

    // Edge and centered paths are both identity on their second application.
    const OffsetClamp edgeAgain = clampOffset(edge.maxLength, edge.offset, Alignment::Edge);
    QCOMPARE(edgeAgain.maxLength, 100.0);
    QCOMPARE(edgeAgain.offset, 0.0);
}

void LengthOffsetClampTest::invariants_afterByStep_gridSweep()
{
    // class invariant (Method criterion c): after any ruler step from any
    // sane-domain state, the result is on-screen, min <= max, and max is
    // inside the ruler's 30..100 rails
    const double maxes[] = {0.0, 1.0, 15.0, 30.0, 42.5, 45.0, 79.0, 80.0, 96.0, 99.0, 100.0};
    const double mins[] = {0.0, 29.0, 30.0, 50.0, 77.5, 100.0};
    const double offsets[] = {-80.0, -35.0, -10.5, 0.0, 0.1, 10.0, 35.0, 49.5, 80.0};
    const double steps[] = {-100.0, -6.0, -0.5, 0.0, 6.0, 100.0};

    for (const double max : maxes) {
        for (const double min : mins) {
            for (const double offset : offsets) {
                for (const double step : steps) {
                    for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                        const LengthState result =
                            clampMaxLengthByStep({max, min, offset}, step, alignment);
                        const auto ctx = QStringLiteral("max=%1 min=%2 off=%3 step=%4 centered=%5")
                                             .arg(max).arg(min).arg(offset).arg(step)
                                             .arg(alignment == Alignment::Centered);
                        QVERIFY2(result.maxLength >= 30.0 && result.maxLength <= 100.0,
                                 qPrintable(ctx));
                        QVERIFY2(result.minLength <= result.maxLength, qPrintable(ctx));
                        QVERIFY2(staysOnScreen(result.maxLength, result.offset, alignment),
                                 qPrintable(ctx));
                    }
                }
            }
        }
    }
}

void LengthOffsetClampTest::invariants_afterToValue_gridSweep()
{
    const double requests[] = {-5.0, 0.0, 0.5, 1.0, 20.0, 50.0, 79.9, 100.0};
    const double mins[] = {0.0, 29.0, 30.0, 50.0, 77.5, 100.0};
    const double offsets[] = {-80.0, -35.0, -10.5, 0.0, 0.1, 10.0, 35.0, 49.5, 80.0};

    for (const double requested : requests) {
        for (const double min : mins) {
            for (const double offset : offsets) {
                for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                    const LengthState result =
                        clampMaxLengthToValue(requested, min, offset, alignment);
                    const auto ctx = QStringLiteral("req=%1 min=%2 off=%3 centered=%4")
                                         .arg(requested).arg(min).arg(offset)
                                         .arg(alignment == Alignment::Centered);
                    QVERIFY2(result.maxLength >= 1.0 && result.maxLength <= 100.0,
                             qPrintable(ctx));
                    QVERIFY2(result.minLength <= result.maxLength, qPrintable(ctx));
                    QVERIFY2(staysOnScreen(result.maxLength, result.offset, alignment),
                             qPrintable(ctx));
                }
            }
        }
    }
}

void LengthOffsetClampTest::idempotence_byStepZeroIsIdentityOnClampedStates()
{
    // spec slot: clamping a clamped state is identity. Every clamped
    // state is a fixed point of a zero step - bit-exact, no epsilon.
    const double maxes[] = {0.0, 15.0, 42.5, 79.0, 96.0, 100.0};
    const double mins[] = {0.0, 30.0, 77.5, 100.0};
    const double offsets[] = {-35.0, -10.5, 0.0, 10.0, 49.5, 80.0};

    for (const double max : maxes) {
        for (const double min : mins) {
            for (const double offset : offsets) {
                for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                    const LengthState clamped =
                        clampMaxLengthByStep({max, min, offset}, -6.0, alignment);
                    const LengthState again = clampMaxLengthByStep(clamped, 0.0, alignment);
                    QCOMPARE(again.maxLength, clamped.maxLength);
                    QCOMPARE(again.minLength, clamped.minLength);
                    QCOMPARE(again.offset, clamped.offset);
                }
            }
        }
    }
}

void LengthOffsetClampTest::idempotence_toValueReapplyIsIdentity()
{
    const double requests[] = {0.0, 0.5, 20.0, 79.9, 100.0};
    const double mins[] = {0.0, 30.0, 77.5, 100.0};
    const double offsets[] = {-35.0, 0.0, 10.0, 49.5, 80.0};

    for (const double requested : requests) {
        for (const double min : mins) {
            for (const double offset : offsets) {
                for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                    const LengthState clamped =
                        clampMaxLengthToValue(requested, min, offset, alignment);
                    const LengthState again = clampMaxLengthToValue(
                        clamped.maxLength, clamped.minLength, clamped.offset, alignment);
                    QCOMPARE(again.maxLength, clamped.maxLength);
                    QCOMPARE(again.minLength, clamped.minLength);
                    QCOMPARE(again.offset, clamped.offset);
                }
            }
        }
    }
}

void LengthOffsetClampTest::idempotence_clampOffsetReapplyIsIdentity()
{
    // One application settles both valid and out-of-domain maximum values.
    const double maxes[] = {0.0, 15.0, 45.5, 79.0, 100.0};
    const double requests[] = {-200.0, -10.5, 0.0, 10.0, 49.5, 200.0};

    for (const double max : maxes) {
        for (const double requested : requests) {
            for (const Alignment alignment : {Alignment::Edge, Alignment::Centered}) {
                const OffsetClamp clamped = clampOffset(max, requested, alignment);
                const OffsetClamp again =
                    clampOffset(clamped.maxLength, clamped.offset, alignment);
                QCOMPARE(again.maxLength, clamped.maxLength);
                QCOMPARE(again.offset, clamped.offset);
            }
        }
    }
}

void LengthOffsetClampTest::crossedUpdates_convergeOnScreenWithMinBelowMax()
{
    // spec slot: min<=max under crossed updates. The Appearance page's
    // wiring after a minLength raise is: minLength is written as-is (no
    // math), then the max slider's update refloors maxLength, which may
    // spill into the offset correction. Replayed through the core:
    LengthState state{90.0, 30.0, 0.0};

    const OffsetClamp afterOffset = clampOffset(state.maxLength, 5.0, Alignment::Centered);
    state.maxLength = afterOffset.maxLength;
    state.offset = afterOffset.offset;
    QCOMPARE(state.maxLength, 90.0);
    QCOMPARE(state.offset, 5.0);

    state.minLength = 95.0;   // the min slider writes freely, crossing max

    const LengthState refloored = clampMaxLengthToValue(state.maxLength, state.minLength,
                                                        state.offset, Alignment::Centered);
    QCOMPARE(refloored.maxLength, 95.0);   // pulled up to min
    QCOMPARE(refloored.offset, 2.5);       // spill recentered: 50 - 95/2
    QVERIFY(refloored.minLength <= refloored.maxLength);
    QVERIFY(staysOnScreen(refloored.maxLength, refloored.offset, Alignment::Centered));
}

void LengthOffsetClampTest::rulerThenSlider_truncationDisagreementIsPinned()
{
    // inherited Qt5 cross-copy seam, pinned as documentation: the ruler's
    // correction can write a fractional offset (50 - 79/2 = 10.5), which
    // the offset slider's truncated int bounds then pull to 10 the next
    // time its update runs. Both copies did exactly this in Qt5; the core
    // preserves it (the truncation IS the int-property conversion).
    const LengthState ruled = clampMaxLengthByStep({73.0, 30.0, 40.0}, 6.0, Alignment::Centered);
    QCOMPARE(ruled.maxLength, 79.0);
    QCOMPARE(ruled.offset, 10.5);

    const OffsetClamp slid = clampOffset(ruled.maxLength, ruled.offset, Alignment::Centered);
    QCOMPARE(slid.maxLength, 79.0);
    QCOMPARE(slid.offset, 10.0);
}

void LengthOffsetClampTest::bridge_mapsAlignmentTotally()
{
    // Latte::Types::Alignment: Center=0 and Justify=10 take the centered
    // branches; every other int (edges, NoneAlignment=-1, garbage from a
    // hand-edited config) behaves as an edge alignment - the same total
    // predicate the shipped QML applied with ===
    Latte::Settings::LengthOffsetClampBridge bridge;

    const struct { int alignment; bool centered; } rows[] = {
        {0, true},    // Center
        {10, true},   // Justify
        {1, false},   // Left
        {2, false},   // Right
        {3, false},   // Top
        {4, false},   // Bottom
        {-1, false},  // NoneAlignment
        {99, false},  // out-of-domain
    };
    for (const auto &row : rows) {
        const double from = bridge.offsetSliderFrom(0.0, row.alignment);
        QCOMPARE(from, row.centered ? -50.0 : 0.0);
        const double to = bridge.offsetSliderTo(0.0, row.alignment);
        QCOMPARE(to, row.centered ? 50.0 : 100.0);
    }
}

void LengthOffsetClampTest::bridge_mapsJustifyToItsOwnFloor()
{
    // D17 through the QML boundary: Justify (Latte::Types::Justify == 10)
    // honours a Maximum below the stored minimum; Center (0) and the edges
    // (1..4) still floor. The geometry stays shared - Justify's offset bounds
    // remain the centered bounds (bridge_mapsAlignmentTotally pins that half).
    Latte::Settings::LengthOffsetClampBridge bridge;

    const QVariantMap justify = bridge.clampMaxLengthToValue(40.0, 50.0, 0.0, 10);
    QCOMPARE(justify.value(QStringLiteral("maxLength")).toDouble(), 40.0);
    QCOMPARE(justify.value(QStringLiteral("minLength")).toDouble(), 50.0);

    for (const int floored : {0, 1, 2, 3, 4}) {   // Center, Left, Right, Top, Bottom
        const QVariantMap map = bridge.clampMaxLengthToValue(40.0, 50.0, 0.0, floored);
        QCOMPARE(map.value(QStringLiteral("maxLength")).toDouble(), 50.0);
    }
}

void LengthOffsetClampTest::bridge_resultsMatchCore()
{
    Latte::Settings::LengthOffsetClampBridge bridge;

    const QVariantMap stepped = bridge.clampMaxLengthByStep(100.0, 100.0, 0.0, -6.0, 0);
    QCOMPARE(stepped.value(QStringLiteral("maxLength")).toDouble(), 94.0);
    QCOMPARE(stepped.value(QStringLiteral("minLength")).toDouble(), 94.0);
    QCOMPARE(stepped.value(QStringLiteral("offset")).toDouble(), 0.0);

    const QVariantMap valued = bridge.clampMaxLengthToValue(95.0, 30.0, 5.0, 10);
    QCOMPARE(valued.value(QStringLiteral("maxLength")).toDouble(), 95.0);
    QCOMPARE(valued.value(QStringLiteral("minLength")).toDouble(), 30.0);
    QCOMPARE(valued.value(QStringLiteral("offset")).toDouble(), 2.5);

    const QVariantMap offsetMap = bridge.clampOffset(79.0, 10.5, 0);
    QCOMPARE(offsetMap.value(QStringLiteral("maxLength")).toDouble(), 79.0);
    QCOMPARE(offsetMap.value(QStringLiteral("offset")).toDouble(), 10.0);
    QVERIFY(!offsetMap.contains(QStringLiteral("minLength")));   // this path never claims it

    QCOMPARE(bridge.offsetSliderFrom(79.0, 0), -10.0);
    QCOMPARE(bridge.offsetSliderTo(79.0, 1), 20.0);
}

void LengthOffsetClampTest::bridge_refusesNonFiniteLoudly()
{
    // the boundary refusal (qCritical-and-refuse; the router wrapper is
    // the model): KConfig parses "nan" into a double, and the Qt5 QML
    // silently pushed it back into the config. The bridge refuses the
    // whole call and returns the input unchanged - no partial clamping
    // of a corrupt state, and the message names the fix.
    Latte::Settings::LengthOffsetClampBridge bridge;
    const QRegularExpression refusal(QStringLiteral("refused: non-finite"));
    const double nan = std::nan("");
    const double inf = std::numeric_limits<double>::infinity();

    QTest::ignoreMessage(QtCriticalMsg, refusal);
    const QVariantMap stepped = bridge.clampMaxLengthByStep(nan, 30.0, 0.0, 6.0, 0);
    QVERIFY(std::isnan(stepped.value(QStringLiteral("maxLength")).toDouble()));
    QCOMPARE(stepped.value(QStringLiteral("minLength")).toDouble(), 30.0);
    QCOMPARE(stepped.value(QStringLiteral("offset")).toDouble(), 0.0);

    QTest::ignoreMessage(QtCriticalMsg, refusal);
    const QVariantMap valued = bridge.clampMaxLengthToValue(50.0, inf, 0.0, 0);
    QVERIFY(std::isinf(valued.value(QStringLiteral("minLength")).toDouble()));

    QTest::ignoreMessage(QtCriticalMsg, refusal);
    const QVariantMap offsetMap = bridge.clampOffset(80.0, nan, 0);
    QCOMPARE(offsetMap.value(QStringLiteral("maxLength")).toDouble(), 80.0);
    QVERIFY(std::isnan(offsetMap.value(QStringLiteral("offset")).toDouble()));

    QTest::ignoreMessage(QtCriticalMsg, refusal);
    // bounds refusal collapses to 0..0: the page disables the offset row
    // when to <= from, so a corrupt maxLength shows as a disabled control
    // plus the log line, never as NaN bounds propagating into the slider
    QCOMPARE(bridge.offsetSliderFrom(nan, 0), 0.0);
    QTest::ignoreMessage(QtCriticalMsg, refusal);
    QCOMPARE(bridge.offsetSliderTo(nan, 0), 0.0);
}

QTEST_GUILESS_MAIN(LengthOffsetClampTest)
#include "lengthoffsetclamptest.moc"
