/*
    SPDX-FileCopyrightText: 2026 Bree Spektor
    SPDX-FileCopyrightText: 2026 Latte Dock contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

// local
#include "../../containment/plugin/maskgeometrybridge.h"
#include "../../containment/plugin/units/maskgeometry.h"

// Qt
#include <QRect>
#include <QRectF>
#include <QTest>

// C++
#include <variant>

using namespace Latte;
using MaskGeometry::AcceptAllInput;
using MaskGeometry::AcceptInputWithin;
using MaskGeometry::AcceptNoInput;
using MaskGeometry::InputMaskDecision;

Q_DECLARE_METATYPE(InputMaskDecision)

//! EX-10 MaskInputGeometry (docs/tracking/QML_EXTRACTION_PLAN.md): the visibility
//! mask (local geometry) and input-region rect tables extracted from
//! VisibilityManager.qml's updateMaskArea/updateInputGeometry pair.
//!
//! Expected values are hand-derived from the per-edge formulas of the QML
//! bodies at the extraction commit (the local-geometry half matches
//! f0ad7b23 verbatim, the input half matches upstream 11f42978), never
//! generated by running the code under test.
//!
//! The shared fixture, used by most rows: a bottom-edge dock in a
//! 1200x140 view window (root item fills it), applets spanning
//! effects.rect x=200 width=800, clean thickness 56, floating screen-edge
//! gap 12. Vertical rows transpose it to 140x800 with effects.rect
//! y=100 height=600.

namespace QTest {
//! decision diagnostics for QCOMPARE failures
template<>
char *toString(const InputMaskDecision &decision)
{
    return std::visit([](const auto &alternative) {
        using T = std::decay_t<decltype(alternative)>;
        if constexpr (std::is_same_v<T, AcceptAllInput>) {
            return qstrdup("AcceptAllInput");
        } else if constexpr (std::is_same_v<T, AcceptInputWithin>) {
            return qstrdup(qPrintable(QStringLiteral("AcceptInputWithin(%1, %2, %3x%4)")
                                              .arg(alternative.rect.x())
                                              .arg(alternative.rect.y())
                                              .arg(alternative.rect.width())
                                              .arg(alternative.rect.height())));
        } else {
            static_assert(std::is_same_v<T, AcceptNoInput>);
            return qstrdup("AcceptNoInput");
        }
    }, decision);
}
}

namespace {

MaskGeometry::LocalGeometryInputs horizontalLocalInputs(Plasma::Types::Location location)
{
    MaskGeometry::LocalGeometryInputs in;
    in.location = location;
    in.behaveAsPlasmaPanel = false;
    in.rootSize = QSizeF(1200, 140);
    in.viewSize = QSize(1200, 140);
    in.effectsRect = QRect(200, 0, 800, 140);
    in.totalsThickness = 56;
    in.screenEdgeMargin = 12;
    return in;
}

MaskGeometry::LocalGeometryInputs verticalLocalInputs(Plasma::Types::Location location)
{
    MaskGeometry::LocalGeometryInputs in;
    in.location = location;
    in.behaveAsPlasmaPanel = false;
    in.rootSize = QSizeF(140, 800);
    in.viewSize = QSize(140, 800);
    in.effectsRect = QRect(0, 100, 140, 600);
    in.totalsThickness = 56;
    in.screenEdgeMargin = 12;
    return in;
}

MaskGeometry::InputMaskInputs horizontalInputMaskInputs(Plasma::Types::Location location)
{
    MaskGeometry::InputMaskInputs in;
    in.location = location;
    in.compositingActive = true;
    in.behaveAsPlasmaPanel = false;
    in.isHidden = false;
    in.isSidebar = false;
    in.parabolicAnimating = false;
    in.floatingGapInputDisabled = false;
    in.hiddenThickness = 2;
    in.zoomedForItemsThickness = 102;
    in.itemsScreenEdgeMargin = 12;
    in.totalsThickness = 56;
    in.maskScreenEdgeMargin = 12;
    in.localGeometry = QRect(200, 72, 800, 56); //! the bottom-edge local geometry
    in.rootSize = QSizeF(1200, 140);
    in.viewSize = QSize(1200, 140);
    return in;
}

MaskGeometry::InputMaskInputs verticalInputMaskInputs(Plasma::Types::Location location)
{
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(location);
    in.localGeometry = QRect(12, 100, 56, 600); //! the left-edge local geometry
    in.rootSize = QSizeF(140, 800);
    in.viewSize = QSize(140, 800);
    return in;
}

}

class MaskGeometryTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    //! local geometry (the mask half)
    void localGeometryPerEdge_data();
    void localGeometryPerEdge();
    void localGeometryPanelUsesFullRootRectUnclamped();
    void localGeometryNonEdgeLocationKeepsFullRootRect();
    void localGeometryClampsIntoViewWindow_data();
    void localGeometryClampsIntoViewWindow();
    void localGeometryWarmupZeroSizePassesThrough();

    //! input region (the input half)
    void inputMaskPerEdgeAndState_data();
    void inputMaskPerEdgeAndState();
    void inputMaskAcceptsEverywhereWithoutCompositing();
    void inputMaskPanelExposesFullWindowSoPopupsAnchorOutside();
    void inputMaskFloatingGapEqualsLocalGeometry();
    void inputMaskAnimatedFloatingGapSubtractsItemsMargin();
    void inputMaskHiddenWinsOverFloatingGap();
    void inputMaskSidebarHiddenAcceptsNothing();
    void inputMaskClampsIntoViewWindow();
    void inputMaskLengthAxisFollowsLocalGeometry();

    //! wrapper boundary (containment/plugin/maskgeometrybridge.cpp,
    //! compiled into this binary per the sanitized-core rule)
    void bridgeComputesLocalGeometry();
    void bridgeMapsAcceptAllToClearRequestRect();
    void bridgeMapsAcceptNoneToBlockAllRect();
    void bridgeConvertsFractionalRectLikeTheQmlAssignmentDid();
    void bridgeRefusesNegativeDimensionsLoudly();
    void bridgeRefusesUnknownLocationLoudly();
};

void MaskGeometryTest::localGeometryPerEdge_data()
{
    QTest::addColumn<int>("location");
    QTest::addColumn<bool>("vertical");
    QTest::addColumn<QRectF>("expected");

    //! horizontal edges: length axis from effects.rect (200..1000),
    //! thickness axis = totals.thickness 56 offset by mask.screenEdge 12
    QTest::newRow("top") << int(Plasma::Types::TopEdge) << false
                         << QRectF(200, 12, 800, 56);
    QTest::newRow("bottom") << int(Plasma::Types::BottomEdge) << false
                            << QRectF(200, 140 - 56 - 12, 800, 56);
    //! vertical edges transpose: length axis from effects.rect (100..700)
    QTest::newRow("left") << int(Plasma::Types::LeftEdge) << true
                          << QRectF(12, 100, 56, 600);
    QTest::newRow("right") << int(Plasma::Types::RightEdge) << true
                           << QRectF(140 - 56 - 12, 100, 56, 600);
}

void MaskGeometryTest::localGeometryPerEdge()
{
    QFETCH(int, location);
    QFETCH(bool, vertical);
    QFETCH(QRectF, expected);

    const auto loc = static_cast<Plasma::Types::Location>(location);
    const MaskGeometry::LocalGeometryInputs in = vertical ? verticalLocalInputs(loc)
                                                          : horizontalLocalInputs(loc);

    QCOMPARE(MaskGeometry::computeLocalGeometry(in), expected);
}

void MaskGeometryTest::localGeometryPanelUsesFullRootRectUnclamped()
{
    //! behaveAsPlasmaPanel keeps the full root rect and skips the clamps
    //! entirely (Qt5: they live inside the !behaveAsPlasmaPanel branch) -
    //! a root transiently larger than the view window must NOT be cut
    MaskGeometry::LocalGeometryInputs in = horizontalLocalInputs(Plasma::Types::BottomEdge);
    in.behaveAsPlasmaPanel = true;
    in.rootSize = QSizeF(1300, 150);
    in.viewSize = QSize(1200, 140);

    QCOMPARE(MaskGeometry::computeLocalGeometry(in), QRectF(0, 0, 1300, 150));
}

void MaskGeometryTest::localGeometryNonEdgeLocationKeepsFullRootRect()
{
    //! the Qt5 if/else-if chain has no branch for non-edge locations
    //! (Floating during very early startup): the initial full root rect
    //! flows through, clamped like any dock rect
    const MaskGeometry::LocalGeometryInputs in = horizontalLocalInputs(Plasma::Types::Floating);

    QCOMPARE(MaskGeometry::computeLocalGeometry(in), QRectF(0, 0, 1200, 140));
}

void MaskGeometryTest::localGeometryClampsIntoViewWindow_data()
{
    QTest::addColumn<QRect>("effectsRect");
    QTest::addColumn<qreal>("totalsThickness");
    QTest::addColumn<qreal>("screenEdgeMargin");
    QTest::addColumn<QRectF>("expected");

    //! thickness + margin exceed the root height: y goes negative and is
    //! floored at 0, the span is capped to the view height (Qt5's
    //! "qBound = qMax(min, qMin(value, max))" comment)
    QTest::newRow("thickness overflow") << QRect(200, 0, 800, 140)
                                        << qreal(200) << qreal(12)
                                        << QRectF(200, 0, 800, 140);
    //! an effects rect wider than the view: width capped, x kept
    QTest::newRow("length overflow") << QRect(0, 0, 1500, 140)
                                     << qreal(56) << qreal(12)
                                     << QRectF(0, 72, 1200, 56);
    //! an effects rect starting beyond the view: x capped AT the view
    //! width (the inherited clamp bounds x into [0, viewWidth]; it does
    //! not re-derive the span - faithful, documented normalization)
    QTest::newRow("origin overflow") << QRect(1300, 0, 100, 140)
                                     << qreal(56) << qreal(12)
                                     << QRectF(1200, 72, 100, 56);
}

void MaskGeometryTest::localGeometryClampsIntoViewWindow()
{
    QFETCH(QRect, effectsRect);
    QFETCH(qreal, totalsThickness);
    QFETCH(qreal, screenEdgeMargin);
    QFETCH(QRectF, expected);

    MaskGeometry::LocalGeometryInputs in = horizontalLocalInputs(Plasma::Types::BottomEdge);
    in.effectsRect = effectsRect;
    in.totalsThickness = totalsThickness;
    in.screenEdgeMargin = screenEdgeMargin;

    QCOMPARE(MaskGeometry::computeLocalGeometry(in), expected);
}

void MaskGeometryTest::localGeometryWarmupZeroSizePassesThrough()
{
    //! the documented warmup protocol (app/view/effects.cpp:330): while
    //! the layouter warms up, zero sizes legitimately flow through and the
    //! degenerate result makes Effects clear the window mask. This must
    //! NOT be refused or "fixed" upward - a loud refusal would fire on
    //! every startup for a legitimate state.
    MaskGeometry::LocalGeometryInputs in;
    in.location = Plasma::Types::BottomEdge;
    in.behaveAsPlasmaPanel = false;
    in.rootSize = QSizeF(0, 0);
    in.viewSize = QSize(0, 0);
    in.effectsRect = QRect(0, 0, 0, 0);
    in.totalsThickness = 56;
    in.screenEdgeMargin = 0;

    const QRectF result = MaskGeometry::computeLocalGeometry(in);
    QCOMPARE(result, QRectF(0, 0, 0, 0));
    QVERIFY(result.isEmpty());
}

void MaskGeometryTest::inputMaskPerEdgeAndState_data()
{
    QTest::addColumn<int>("location");
    QTest::addColumn<bool>("vertical");
    QTest::addColumn<bool>("isHidden");
    QTest::addColumn<bool>("parabolicAnimating");
    QTest::addColumn<InputMaskDecision>("expected");

    //! normal state: thickness = mask.screenEdge 12 + totals.thickness 56
    //! = 68, length axis from localGeometry
    QTest::newRow("top normal") << int(Plasma::Types::TopEdge) << false << false << false
                                << InputMaskDecision(AcceptInputWithin{QRectF(200, 0, 800, 68)});
    QTest::newRow("bottom normal") << int(Plasma::Types::BottomEdge) << false << false << false
                                   << InputMaskDecision(AcceptInputWithin{QRectF(200, 140 - 68, 800, 68)});
    QTest::newRow("left normal") << int(Plasma::Types::LeftEdge) << true << false << false
                                 << InputMaskDecision(AcceptInputWithin{QRectF(0, 100, 68, 600)});
    QTest::newRow("right normal") << int(Plasma::Types::RightEdge) << true << false << false
                                  << InputMaskDecision(AcceptInputWithin{QRectF(140 - 68, 100, 68, 600)});

    //! hidden: a 2px reveal strip on the screen edge, length axis still
    //! from localGeometry
    QTest::newRow("top hidden") << int(Plasma::Types::TopEdge) << false << true << false
                                << InputMaskDecision(AcceptInputWithin{QRectF(200, 0, 800, 2)});
    QTest::newRow("bottom hidden") << int(Plasma::Types::BottomEdge) << false << true << false
                                   << InputMaskDecision(AcceptInputWithin{QRectF(200, 138, 800, 2)});
    QTest::newRow("left hidden") << int(Plasma::Types::LeftEdge) << true << true << false
                                 << InputMaskDecision(AcceptInputWithin{QRectF(0, 100, 2, 600)});
    QTest::newRow("right hidden") << int(Plasma::Types::RightEdge) << true << true << false
                                  << InputMaskDecision(AcceptInputWithin{QRectF(138, 100, 2, 600)});

    //! parabolic zoom in flight (upstream 11f42978): the length axis
    //! widens to the full root span (localGeometry is NOT read) and the
    //! thickness grows to mask.thickness.zoomedForItems 102, so the
    //! zoomed item's outer pixels keep receiving input instead of
    //! flapping enter/exit
    QTest::newRow("top animated") << int(Plasma::Types::TopEdge) << false << false << true
                                  << InputMaskDecision(AcceptInputWithin{QRectF(0, 0, 1200, 102)});
    QTest::newRow("bottom animated") << int(Plasma::Types::BottomEdge) << false << false << true
                                     << InputMaskDecision(AcceptInputWithin{QRectF(0, 140 - 102, 1200, 102)});
    QTest::newRow("left animated") << int(Plasma::Types::LeftEdge) << true << false << true
                                   << InputMaskDecision(AcceptInputWithin{QRectF(0, 0, 102, 800)});
    QTest::newRow("right animated") << int(Plasma::Types::RightEdge) << true << false << true
                                    << InputMaskDecision(AcceptInputWithin{QRectF(140 - 102, 0, 102, 800)});
}

void MaskGeometryTest::inputMaskPerEdgeAndState()
{
    QFETCH(int, location);
    QFETCH(bool, vertical);
    QFETCH(bool, isHidden);
    QFETCH(bool, parabolicAnimating);
    QFETCH(InputMaskDecision, expected);

    const auto loc = static_cast<Plasma::Types::Location>(location);
    MaskGeometry::InputMaskInputs in = vertical ? verticalInputMaskInputs(loc)
                                                : horizontalInputMaskInputs(loc);
    in.isHidden = isHidden;
    in.parabolicAnimating = parabolicAnimating;

    QCOMPARE(MaskGeometry::computeInputMask(in), expected);
}

void MaskGeometryTest::inputMaskAcceptsEverywhereWithoutCompositing()
{
    //! without compositing there is no mask to align with, so the whole
    //! window accepts input (the legacy fall-through)
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.compositingActive = false;
    QCOMPARE(MaskGeometry::computeInputMask(in), InputMaskDecision(AcceptAllInput{}));
}

void MaskGeometryTest::inputMaskPanelExposesFullWindowSoPopupsAnchorOutside()
{
    //! REGRESSION (Issue 2, panel popup opens over the panel): a
    //! behaveAsPlasmaPanel window must expose its WHOLE window as the input
    //! mask, not clear it. libplasma's PopupPlasmaWindow anchors an applet
    //! popup to parentWindow->mask().boundingRect(); a cleared mask collapses
    //! that to a 1px strip at the window top and the popup opens OVER the
    //! panel (covering the icon), while a masked dock's real band anchors it
    //! outside. A cleared mask (the old AcceptAllInput here) would put the
    //! bounding rect at 0-height and reintroduce the bug.
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.behaveAsPlasmaPanel = true;
    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(0, 0, 1200, 140)}));

    //! same on a vertical panel: the full window, no axis narrowed
    MaskGeometry::InputMaskInputs vin = verticalInputMaskInputs(Plasma::Types::LeftEdge);
    vin.behaveAsPlasmaPanel = true;
    QCOMPARE(MaskGeometry::computeInputMask(vin),
             InputMaskDecision(AcceptInputWithin{QRectF(0, 0, 140, 800)}));

    //! the exposed band spans the full thickness so the popup anchors at the
    //! real panel edge (bottom() here), never a collapsed strip at the top
    const auto decision = MaskGeometry::computeInputMask(in);
    const QRectF band = std::get<AcceptInputWithin>(decision).rect;
    QCOMPARE(band.top(), qreal(0));
    QCOMPARE(band.bottom(), qreal(140));
}

void MaskGeometryTest::inputMaskFloatingGapEqualsLocalGeometry()
{
    //! floating dock with gap input events disabled, normal state: the
    //! input band hugs the applets exactly - thickness totals.thickness,
    //! offset by the subtracted screen edge - so the input rect EQUALS
    //! the local geometry (the spec's mask==input equivalence)
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.floatingGapInputDisabled = true;

    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(in.localGeometry)}));
}

void MaskGeometryTest::inputMaskAnimatedFloatingGapSubtractsItemsMargin()
{
    //! animated + floating gap disabled: zoomedForItems already contains
    //! margin.screenEdge (Metrics.qml:92), so the gap's share is removed
    //! from the thickness and the band is offset by the subtracted
    //! screen edge: thickness = 102 - 12 = 90, y = 140 - 90 - 12
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.parabolicAnimating = true;
    in.floatingGapInputDisabled = true;

    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(0, 38, 1200, 90)}));
}

void MaskGeometryTest::inputMaskHiddenWinsOverFloatingGap()
{
    //! isHidden is checked first: a hidden floating dock keeps the 2px
    //! reveal strip ON the screen edge (subtractedScreenEdge only applies
    //! when not hidden)
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.isHidden = true;
    in.floatingGapInputDisabled = true;

    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(200, 138, 800, 2)}));
}

void MaskGeometryTest::inputMaskSidebarHiddenAcceptsNothing()
{
    //! a hidden sidebar accepts no input anywhere - there is no reveal
    //! strip, showing is on demand
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.isHidden = true;
    in.isSidebar = true;

    QCOMPARE(MaskGeometry::computeInputMask(in), InputMaskDecision(AcceptNoInput{}));
}

void MaskGeometryTest::inputMaskClampsIntoViewWindow()
{
    //! a zoomed thickness taller than the window: y floors at 0 and the
    //! span caps at the view height (same inherited clamps as the mask)
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.parabolicAnimating = true;
    in.zoomedForItemsThickness = 300;

    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(0, 0, 1200, 140)}));
}

void MaskGeometryTest::inputMaskLengthAxisFollowsLocalGeometry()
{
    //! whatever localGeometry says the applet span is, the non-animated
    //! input band follows it verbatim on the length axis
    MaskGeometry::InputMaskInputs in = horizontalInputMaskInputs(Plasma::Types::BottomEdge);
    in.localGeometry = QRect(444, 72, 313, 56);

    QCOMPARE(MaskGeometry::computeInputMask(in),
             InputMaskDecision(AcceptInputWithin{QRectF(444, 72, 313, 68)}));
}

void MaskGeometryTest::bridgeComputesLocalGeometry()
{
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.localGeometryFor(Plasma::Types::BottomEdge,
                                     /*behaveAsPlasmaPanel*/ false,
                                     1200, 140, 1200, 140,
                                     QRect(200, 0, 800, 140),
                                     56, 12),
             QRect(200, 72, 800, 56));
}

void MaskGeometryTest::bridgeMapsAcceptAllToClearRequestRect()
{
    //! Qt.rect(0,0,-1,-1) is Effects::setInputMask's explicit clear
    //! request (app/view/effects.cpp) - it exists only at this boundary,
    //! mapped from the AcceptAllInput alternative
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.inputMaskFor(Plasma::Types::BottomEdge,
                                 /*compositingActive*/ false,
                                 /*behaveAsPlasmaPanel*/ false,
                                 /*isHidden*/ false, /*isSidebar*/ false,
                                 /*parabolicAnimating*/ false,
                                 /*floatingGapInputDisabled*/ false,
                                 2, 102, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 1200, 140, 1200, 140),
             QRect(0, 0, -1, -1));
}

void MaskGeometryTest::bridgeMapsAcceptNoneToBlockAllRect()
{
    //! Qt.rect(-1,-1,1,1): a 1px rect offscreen, upstream's "no input is
    //! accepted anywhere" encoding for hidden sidebars
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.inputMaskFor(Plasma::Types::BottomEdge,
                                 true, false,
                                 /*isHidden*/ true, /*isSidebar*/ true,
                                 false, false,
                                 2, 102, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 1200, 140, 1200, 140),
             QRect(-1, -1, 1, 1));
}

void MaskGeometryTest::bridgeConvertsFractionalRectLikeTheQmlAssignmentDid()
{
    //! Before the extraction the QML assigned a fractional Qt.rect to the
    //! QRect Q_PROPERTY and Qt converted it via QRectF::toRect(). The
    //! bridge must convert identically. Expected values follow Qt 6's
    //! toRect (qrect.h): y' = round(y), h' = round(h + (y - y')/2):
    //! y = 140 - 91.4 = 48.6 -> 49, h = round(91.4 + (48.6 - 49)/2)
    //!   = round(91.2) = 91.
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.inputMaskFor(Plasma::Types::BottomEdge,
                                 true, false,
                                 false, false,
                                 /*parabolicAnimating*/ true, false,
                                 2, /*zoomedForItems*/ 91.4, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 1200, 140, 1200, 140),
             QRect(0, 49, 1200, 91));
}

void MaskGeometryTest::bridgeRefusesNegativeDimensionsLoudly()
{
    //! negative sizes and thicknesses are never-states (no producer emits
    //! them; zero is the warmup protocol, negative is a bug upstream of
    //! the call). The bridge refuses loudly (qCritical in the log) and
    //! degrades safely: an empty local geometry (the consumer's clear
    //! path) and an accept-everywhere input mask (a refused call must
    //! never brick input).
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.localGeometryFor(Plasma::Types::BottomEdge, false,
                                     -5, 140, 1200, 140,
                                     QRect(200, 0, 800, 140), 56, 12),
             QRect());
    QCOMPARE(bridge.localGeometryFor(Plasma::Types::BottomEdge, false,
                                     1200, 140, 1200, -3,
                                     QRect(200, 0, 800, 140), 56, 12),
             QRect());
    QCOMPARE(bridge.localGeometryFor(Plasma::Types::BottomEdge, false,
                                     1200, 140, 1200, 140,
                                     QRect(200, 0, 800, 140), -1, 12),
             QRect());

    QCOMPARE(bridge.inputMaskFor(Plasma::Types::BottomEdge,
                                 true, false, false, false, false, false,
                                 -2, 102, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 1200, 140, 1200, 140),
             QRect(0, 0, -1, -1));
    QCOMPARE(bridge.inputMaskFor(Plasma::Types::BottomEdge,
                                 true, false, false, false, false, false,
                                 2, 102, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 -7, 140, 1200, 140),
             QRect(0, 0, -1, -1));
}

void MaskGeometryTest::bridgeRefusesUnknownLocationLoudly()
{
    //! an int outside Plasma::Types::Location is a caller bug; refuse
    //! loudly with the same safe degradations
    Containment::MaskGeometryBridge bridge;

    QCOMPARE(bridge.localGeometryFor(99, false,
                                     1200, 140, 1200, 140,
                                     QRect(200, 0, 800, 140), 56, 12),
             QRect());
    QCOMPARE(bridge.inputMaskFor(-1,
                                 true, false, false, false, false, false,
                                 2, 102, 12, 56, 12,
                                 QRect(200, 72, 800, 56),
                                 1200, 140, 1200, 140),
             QRect(0, 0, -1, -1));
}

QTEST_GUILESS_MAIN(MaskGeometryTest)

#include "maskgeometrytest.moc"
