/*
    SPDX-FileCopyrightText: 2026 Bree Spektor
    SPDX-FileCopyrightText: 2026 Latte Dock contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

// EX-17 TooltipTextComposer (docs/tracking/QML_EXTRACTION_PLAN.md): behavioral tests
// for the tooltip title/subtext core and its QML-facing wrapper (compiled
// into this sanitized binary, so the boundary refusals and the i18n mapping
// run instrumented too).
//
// Reference values: generated by driving the SHIPPED pre-extraction
// ToolTipInstance.qml offscreen through tests/qml/tst_tooltiptext.qml at
// commit 1ed62d89 (the suite instantiates the real component and asserts
// these same strings; it stays green across the cutover, which is the
// twin-equivalence evidence). The i18n-mapped strings are the English
// msgids - the offscreen environments load no catalogs, deterministically.

#include <QtTest>

#include "../../plasmoid/plugin/tooltiptextcomposer.h"
#include "../../plasmoid/plugin/units/tooltiptext.h"

using namespace Latte::TooltipText;

namespace {

//! the em-dash placeholder composeTitle falls back to
const QString placeholder = QStringLiteral("—");

SubTextFacts baseFacts()
{
    SubTextFacts facts;
    facts.showOnlyCurrentDesktop = false;
    facts.showOnlyCurrentActivity = true;
    facts.desktopCount = 3;
    facts.runningActivityCount = 1;
    facts.onAllVirtualDesktops = false;
    facts.activities = QList<Activity>{};
    facts.currentActivityId = QStringLiteral("curA");
    return facts;
}

}

class TooltipTextTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    void composeTitle_referenceTable_data();
    void composeTitle_referenceTable();
    void composeTitle_invalidAppNamePatternSkipsStrip();

    void planSubText_desktopLine();
    void planSubText_desktopLineNeverEmpty();
    void planSubText_activityLines();
    void planSubText_unknownActivitiesRole();
    void planSubText_degenerateInputs();

    void wrapper_composesTheQmlSuiteStrings();
    void wrapper_refusesMalformedFacts();

    void planAccessibleDescription_tokenSelectionAndOrder();
    void wrapper_composesAccessibleDescriptions();
    void wrapper_refusesMalformedAccessibleFacts();
};

void TooltipTextTest::composeTitle_referenceTable_data()
{
    QTest::addColumn<QString>("display");
    QTest::addColumn<QString>("appName");
    QTest::addColumn<QString>("expected");

    // vectors recorded from the shipped QML (see file header)
    QTest::newRow("emdash appName suffix")
        << QStringLiteral("index.html — Firefox") << QStringLiteral("Firefox")
        << QStringLiteral("index.html");
    QTest::newRow("hyphen appName suffix")
        << QStringLiteral("index.html - Firefox") << QStringLiteral("Firefox")
        << QStringLiteral("index.html");
    QTest::newRow("counter survives appName strip")
        << QStringLiteral("index.html — Firefox <2>") << QStringLiteral("Firefox")
        << QStringLiteral("index.html <2>");
    QTest::newRow("counter without appName")
        << QStringLiteral("index.html <2>") << QStringLiteral("Firefox")
        << QStringLiteral("index.html <2>");
    QTest::newRow("counter keeps its trailing space")
        << QStringLiteral("index.html <2> ") << QStringLiteral("Firefox")
        << QStringLiteral("index.html <2> ");
    QTest::newRow("counter keeps trailing punctuation")
        << QStringLiteral("index.html <2>!!") << QStringLiteral("Firefox")
        << QStringLiteral("index.html <2>!!");
    QTest::newRow("only appName becomes placeholder")
        << QStringLiteral("Firefox") << QStringLiteral("Firefox")
        << placeholder;
    QTest::newRow("only appName and counter leaves counter")
        << QStringLiteral("Firefox <2>") << QStringLiteral("Firefox")
        << QStringLiteral("<2>");
    QTest::newRow("appName strip is case-insensitive")
        << QStringLiteral("doc - FIREFOX") << QStringLiteral("Firefox")
        << QStringLiteral("doc");
    QTest::newRow("non-numeric angle brackets kept")
        << QStringLiteral("a <b> tags — Firefox") << QStringLiteral("Firefox")
        << QStringLiteral("a <b> tags");
    QTest::newRow("counter after other angle brackets")
        << QStringLiteral("a <b> <2>") << QStringLiteral("Firefox")
        << QStringLiteral("a <b> <2>");
    QTest::newRow("empty display becomes placeholder")
        << QString() << QStringLiteral("Firefox")
        << placeholder;
    // JS \s is unicode-aware; the core's spelled-out class must strip the
    // NBSP exactly like Qt5's JS did
    QTest::newRow("NBSP stripped with the separator")
        << QStringLiteral("doc\u00a0\u2014 Firefox") << QStringLiteral("Firefox")
        << QStringLiteral("doc");
    QTest::newRow("inner separators kept")
        << QStringLiteral("a — b — Firefox") << QStringLiteral("Firefox")
        << QStringLiteral("a — b");
    QTest::newRow("trailing dash run stripped")
        << QStringLiteral("trailing dashes -- ") << QStringLiteral("Firefox")
        << QStringLiteral("trailing dashes");
    // Qt5 built the appName regex UNESCAPED: a valid metachar pattern
    // matches both its literal and wildcard forms
    QTest::newRow("metachar appName literal form")
        << QStringLiteral("notes - Node.js") << QStringLiteral("Node.js")
        << QStringLiteral("notes");
    QTest::newRow("metachar appName wildcard form")
        << QStringLiteral("notes - NodeXjs") << QStringLiteral("Node.js")
        << QStringLiteral("notes");
    QTest::newRow("empty appName strips nothing")
        << QStringLiteral("plain title") << QString()
        << QStringLiteral("plain title");
    // only the LAST counter is a counter; an earlier one is title text
    // (leftmost-first backtracking, identical in JS and PCRE2; asserted
    // against the shipped QML in tst_tooltiptext.qml)
    QTest::newRow("two counters keep the first as text")
        << QStringLiteral("x <2> <3>") << QStringLiteral("Firefox")
        << QStringLiteral("x <2> <3>");
    QTest::newRow("counter only")
        << QStringLiteral("<7>") << QStringLiteral("Firefox")
        << QStringLiteral("<7>");
    QTest::newRow("counter inside kept, last counter restored with its space")
        << QStringLiteral("a <2> b <3> ") << QStringLiteral("Firefox")
        << QStringLiteral("a <2> b <3> ");
    // the separator strip is one contiguous ws-dashes-ws run: a dash-space-
    // dash tail strips only from the last run's start
    QTest::newRow("dash space dash strips the last run only")
        << QStringLiteral("a - - ") << QStringLiteral("Firefox")
        << QStringLiteral("a -");
    QTest::newRow("empty display and appName")
        << QString() << QString()
        << placeholder;
}

void TooltipTextTest::composeTitle_referenceTable()
{
    QFETCH(QString, display);
    QFETCH(QString, appName);
    QFETCH(QString, expected);

    QCOMPARE(composeTitle(display, appName), expected);
}

void TooltipTextTest::composeTitle_invalidAppNamePatternSkipsStrip()
{
    // deliberate divergence from Qt5 (commented in the core): JS THREW on
    // new RegExp("Notepad++$") and broke the whole title binding; the core
    // skips the strip and keeps the full title
    QCOMPARE(composeTitle(QStringLiteral("doc - Notepad++"), QStringLiteral("Notepad++")),
             QStringLiteral("doc - Notepad++"));
}

void TooltipTextTest::planSubText_desktopLine()
{
    SubTextFacts facts = baseFacts();
    facts.desktopNames = QStringList{QStringLiteral("Two")};
    QCOMPARE(planSubText(facts).desktopNamesJoined, QStringLiteral("Two"));

    // Qt5 joined with JS [].join(): comma, no space
    facts.desktopNames = QStringList{QStringLiteral("One"), QStringLiteral("Three")};
    QCOMPARE(planSubText(facts).desktopNamesJoined, QStringLiteral("One,Three"));

    facts.showOnlyCurrentDesktop = true;
    QVERIFY(!planSubText(facts).desktopNamesJoined);

    facts = baseFacts();
    facts.desktopNames = QStringList{QStringLiteral("Two")};
    facts.desktopCount = 1;
    QVERIFY(!planSubText(facts).desktopNamesJoined);

    facts = baseFacts();
    facts.desktopNames = QStringList{QStringLiteral("Two")};
    facts.onAllVirtualDesktops = true;
    QVERIFY(!planSubText(facts).desktopNamesJoined);
}

void TooltipTextTest::planSubText_desktopLineNeverEmpty()
{
    // the eliminated invalid state "On <nothing>": an empty resolved-name
    // list (all ids stale) produces NO line, never an empty argument
    SubTextFacts facts = baseFacts();
    facts.desktopNames = QStringList{};
    const SubTextPlan plan = planSubText(facts);
    QVERIFY(!plan.desktopNamesJoined);

    // and a present argument is never the empty string
    facts.desktopNames = QStringList{QStringLiteral("Two")};
    const SubTextPlan shown = planSubText(facts);
    QVERIFY(shown.desktopNamesJoined);
    QVERIFY(!shown.desktopNamesJoined->isEmpty());
}

void TooltipTextTest::planSubText_activityLines()
{
    const Activity current{QStringLiteral("curA"), QStringLiteral("Current")};
    const Activity work{QStringLiteral("actB"), QStringLiteral("Work")};
    const Activity play{QStringLiteral("actC"), QStringLiteral("Play")};
    const Activity unnamed{QStringLiteral("unnamed"), QString()};

    // empty activity list: available on all - but only when more than one
    // activity is running
    SubTextFacts facts = baseFacts();
    facts.runningActivityCount = 2;
    QCOMPARE(planSubText(facts).activitiesLine,
             std::optional<ActivitiesLine>(AvailableOnAllActivities{}));

    facts.runningActivityCount = 1;
    QVERIFY(!planSubText(facts).activitiesLine);

    // the current activity is always filtered out
    facts = baseFacts();
    facts.activities = QList<Activity>{current};
    QVERIFY(!planSubText(facts).activitiesLine);

    facts.activities = QList<Activity>{current, work};
    QCOMPARE(planSubText(facts).activitiesLine,
             std::optional<ActivitiesLine>(AlsoAvailableOnActivities{QStringLiteral("Work")}));

    // showOnlyCurrentActivity picks the message variant, not the filter
    facts.showOnlyCurrentActivity = false;
    QCOMPARE(planSubText(facts).activitiesLine,
             std::optional<ActivitiesLine>(AvailableOnActivities{QStringLiteral("Work")}));

    facts.activities = QList<Activity>{current, work, play};
    QCOMPARE(planSubText(facts).activitiesLine,
             std::optional<ActivitiesLine>(AvailableOnActivities{QStringLiteral("Work, Play")}));

    // activities whose name lookup came back empty are skipped
    facts = baseFacts();
    facts.activities = QList<Activity>{unnamed, work};
    QCOMPARE(planSubText(facts).activitiesLine,
             std::optional<ActivitiesLine>(AlsoAvailableOnActivities{QStringLiteral("Work")}));

    facts.activities = QList<Activity>{unnamed};
    QVERIFY(!planSubText(facts).activitiesLine);
}

void TooltipTextTest::planSubText_unknownActivitiesRole()
{
    // the TaskItem twin's shape: Activities role unknown (nullopt, the
    // eliminated "undefined vs empty" ambiguity) - the desktop line still
    // shows, the activity lines cannot
    SubTextFacts facts = baseFacts();
    facts.activities = std::nullopt;
    facts.desktopNames = QStringList{QStringLiteral("Two")};
    facts.runningActivityCount = 5;

    const SubTextPlan plan = planSubText(facts);
    QCOMPARE(plan.desktopNamesJoined, QStringLiteral("Two"));
    QVERIFY(!plan.activitiesLine);
}

void TooltipTextTest::planSubText_degenerateInputs()
{
    // default-constructed facts: nothing to say, empty plan
    QCOMPARE(planSubText(SubTextFacts{}), SubTextPlan{});

    // zero running activities with an empty list stays silent (boundary
    // below the >1 threshold)
    SubTextFacts facts = baseFacts();
    facts.runningActivityCount = 0;
    QVERIFY(!planSubText(facts).activitiesLine);

    // empty-string ids: an activity whose id equals the (empty) current id
    // is the current activity and filters out
    facts = baseFacts();
    facts.currentActivityId = QString();
    facts.activities = QList<Activity>{Activity{QString(), QStringLiteral("Ghost")}};
    QVERIFY(!planSubText(facts).activitiesLine);
}

void TooltipTextTest::wrapper_composesTheQmlSuiteStrings()
{
    // end-to-end through the wrapper: same facts the cutover shells send,
    // same strings tests/qml/tst_tooltiptext.qml asserts against the
    // shipped QML (English msgids - no catalogs offscreen)
    const Latte::Tasks::TooltipTextComposer composer;

    QVariantMap facts{
        {QStringLiteral("showOnlyCurrentDesktop"), false},
        {QStringLiteral("showOnlyCurrentActivity"), true},
        {QStringLiteral("desktopCount"), 3},
        {QStringLiteral("runningActivityCount"), 1},
        {QStringLiteral("onAllVirtualDesktops"), false},
        {QStringLiteral("desktopNames"), QStringList{QStringLiteral("Two")}},
        {QStringLiteral("activityIds"), QStringList{QStringLiteral("actB")}},
        {QStringLiteral("activityNames"), QStringList{QStringLiteral("Work")}},
        {QStringLiteral("currentActivity"), QStringLiteral("curA")},
    };
    QCOMPARE(composer.composeSubText(facts),
             QStringLiteral("On Two\nAlso available on Work"));

    facts[QStringLiteral("showOnlyCurrentActivity")] = false;
    QCOMPARE(composer.composeSubText(facts),
             QStringLiteral("On Two\nAvailable on Work"));

    facts[QStringLiteral("activityIds")] = QStringList{};
    facts[QStringLiteral("activityNames")] = QStringList{};
    facts[QStringLiteral("runningActivityCount")] = 2;
    QCOMPARE(composer.composeSubText(facts),
             QStringLiteral("On Two\nAvailable on all activities"));

    // the unknown-role shape: null id/name lists travel as nullopt
    facts[QStringLiteral("activityIds")] = QVariant();
    facts[QStringLiteral("activityNames")] = QVariant();
    QCOMPARE(composer.composeSubText(facts), QStringLiteral("On Two"));

    QCOMPARE(composer.composeTitle(QStringLiteral("index.html — Firefox <2>"),
                                   QStringLiteral("Firefox")),
             QStringLiteral("index.html <2>"));
}

void TooltipTextTest::wrapper_refusesMalformedFacts()
{
    const Latte::Tasks::TooltipTextComposer composer;

    // a missing fact key is a drifted shell: refuse loudly, compose nothing
    QCOMPARE(composer.composeSubText(QVariantMap{}), QString());

    QVariantMap facts{
        {QStringLiteral("showOnlyCurrentDesktop"), false},
        {QStringLiteral("showOnlyCurrentActivity"), true},
        {QStringLiteral("desktopCount"), 3},
        {QStringLiteral("runningActivityCount"), 1},
        {QStringLiteral("onAllVirtualDesktops"), false},
        {QStringLiteral("desktopNames"), QStringList{QStringLiteral("Two")}},
        {QStringLiteral("activityIds"), QStringList{QStringLiteral("actB")}},
        {QStringLiteral("activityNames"), QStringList{QStringLiteral("Work")}},
        {QStringLiteral("currentActivity"), QStringLiteral("curA")},
    };

    // the eliminated invalid state "parallel id/name lists drifting":
    // a length mismatch cannot reach the core
    QVariantMap mismatched = facts;
    mismatched[QStringLiteral("activityNames")] =
        QStringList{QStringLiteral("Work"), QStringLiteral("Play")};
    QCOMPARE(composer.composeSubText(mismatched), QString());

    // ids and names must be null together
    QVariantMap halfNull = facts;
    halfNull[QStringLiteral("activityIds")] = QVariant();
    QCOMPARE(composer.composeSubText(halfNull), QString());

    // and the well-formed original still composes (the refusals above were
    // the map's doing, not leftover state)
    QCOMPARE(composer.composeSubText(facts),
             QStringLiteral("On Two\nAlso available on Work"));
}

void TooltipTextTest::planAccessibleDescription_tokenSelectionAndOrder()
{
    // nothing shown, nothing announced
    QVERIFY(planAccessibleDescription(AccessibleDescriptionFacts{}).isEmpty());

    // a plain single window: the name already carries the title, so the
    // description stays empty
    AccessibleDescriptionFacts facts;
    facts.windowsCount = 1;
    QVERIFY(planAccessibleDescription(facts).isEmpty());

    // launcher kind announces itself
    facts = {};
    facts.isLauncher = true;
    QCOMPARE(planAccessibleDescription(facts),
             (QList<AccessibleAnnouncement>{LauncherAnnouncement{}}));

    // group parent announces its window count; a groupless windowsCount
    // does not (single windows say nothing beyond the name)
    facts = {};
    facts.isGroupParent = true;
    facts.windowsCount = 3;
    QCOMPARE(planAccessibleDescription(facts),
             (QList<AccessibleAnnouncement>{WindowCountAnnouncement{3}}));

    // a group whose windows just closed (count 0) has nothing to count
    facts.windowsCount = 0;
    QVERIFY(planAccessibleDescription(facts).isEmpty());

    // audio badge: muted wins over playing (the badge draws the muted icon)
    facts = {};
    facts.showsAudioBadge = true;
    QCOMPARE(planAccessibleDescription(facts),
             (QList<AccessibleAnnouncement>{PlayingAudioAnnouncement{}}));
    facts.isMuted = true;
    QCOMPARE(planAccessibleDescription(facts),
             (QList<AccessibleAnnouncement>{AudioMutedAnnouncement{}}));

    // muted without a shown badge stays silent - the flag qualifies the
    // badge, it is not an announcement of its own
    facts = {};
    facts.isMuted = true;
    QVERIFY(planAccessibleDescription(facts).isEmpty());

    // everything at once: kind, group size, then badges in audio,
    // progress, info order
    facts = {};
    facts.isGroupParent = true;
    facts.windowsCount = 2;
    facts.showsAudioBadge = true;
    facts.showsProgressBadge = true;
    facts.progressPercent = 45;
    facts.infoBadgeCount = 7;
    QCOMPARE(planAccessibleDescription(facts),
             (QList<AccessibleAnnouncement>{WindowCountAnnouncement{2},
                                            PlayingAudioAnnouncement{},
                                            ProgressAnnouncement{45},
                                            InfoBadgeAnnouncement{7}}));
}

void TooltipTextTest::wrapper_composesAccessibleDescriptions()
{
    // end-to-end through the wrapper: same fact bag TaskItem.qml sends,
    // asserted as English msgids (no catalogs offscreen). The qmltest
    // twin tests/qml/tst_taskaccessible.qml drives the SHIPPED singleton
    // through the module import with these same vectors.
    const Latte::Tasks::TooltipTextComposer composer;

    QVariantMap facts{
        {QStringLiteral("isLauncher"), false},
        {QStringLiteral("isGroupParent"), false},
        {QStringLiteral("windowsCount"), 0},
        {QStringLiteral("showsAudioBadge"), false},
        {QStringLiteral("isMuted"), false},
        {QStringLiteral("showsProgressBadge"), false},
        {QStringLiteral("progressPercent"), 0},
        {QStringLiteral("infoBadgeCount"), 0},
    };
    QCOMPARE(composer.composeAccessibleDescription(facts), QString());

    QVariantMap launcher = facts;
    launcher[QStringLiteral("isLauncher")] = true;
    QCOMPARE(composer.composeAccessibleDescription(launcher), QStringLiteral("launcher"));

    QVariantMap group = facts;
    group[QStringLiteral("isGroupParent")] = true;
    group[QStringLiteral("windowsCount")] = 1;
    QCOMPARE(composer.composeAccessibleDescription(group), QStringLiteral("1 window"));
    group[QStringLiteral("windowsCount")] = 4;
    QCOMPARE(composer.composeAccessibleDescription(group), QStringLiteral("4 windows"));

    QVariantMap loaded = facts;
    loaded[QStringLiteral("isGroupParent")] = true;
    loaded[QStringLiteral("windowsCount")] = 2;
    loaded[QStringLiteral("showsAudioBadge")] = true;
    loaded[QStringLiteral("isMuted")] = true;
    loaded[QStringLiteral("showsProgressBadge")] = true;
    loaded[QStringLiteral("progressPercent")] = 45;
    loaded[QStringLiteral("infoBadgeCount")] = 7;
    QCOMPARE(composer.composeAccessibleDescription(loaded),
             QStringLiteral("2 windows, audio muted, 45% complete, 7 notifications"));

    QCOMPARE(composer.muteToggleLabel(), QStringLiteral("Mute"));
}

void TooltipTextTest::wrapper_refusesMalformedAccessibleFacts()
{
    const Latte::Tasks::TooltipTextComposer composer;

    // a missing fact key is a drifted shell: refuse loudly, compose nothing
    QCOMPARE(composer.composeAccessibleDescription(QVariantMap{}), QString());

    QVariantMap partial{
        {QStringLiteral("isLauncher"), true},
        {QStringLiteral("isGroupParent"), false},
        {QStringLiteral("windowsCount"), 0},
        {QStringLiteral("showsAudioBadge"), false},
        {QStringLiteral("isMuted"), false},
        {QStringLiteral("showsProgressBadge"), false},
        {QStringLiteral("progressPercent"), 0},
    };
    // infoBadgeCount missing
    QCOMPARE(composer.composeAccessibleDescription(partial), QString());

    // and completing the bag composes (the refusal was the map's doing)
    partial[QStringLiteral("infoBadgeCount")] = 0;
    QCOMPARE(composer.composeAccessibleDescription(partial), QStringLiteral("launcher"));
}

QTEST_GUILESS_MAIN(TooltipTextTest)

#include "tooltiptexttest.moc"
